### ISSUE TITLE
配置云上的oss 数据源之后，在pad中进行隐私求交之后出现报错

### ISSUE THREAD

**Issue by john8628** [secretflow/secretpad#104]
### Issue Type

Document

### Have you searched for existing issues?

Yes

### Link to Relevant Documentation

https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.7.0b0/p2p_deploy/function_description/data_source

### Question Details

```shell
在页面上配置oss数据源之后，隐私求交的时候，出现如下报错
 2024-07-12 03:27:33,392|transsion|INFO|secretflow|entry.py:start_ray:81| Succeeded to start ray head node at roqt-eowynlee-node-35-0-global.transsion.svc.
2024-07-12T11:27:33.393523372+08:00 stdout F 2024-07-12 03:27:33,393|transsion|INFO|secretflow|entry.py:main:510| datasource.access_directly True
2024-07-12T11:27:33.393536451+08:00 stdout F sf_node_eval_param  {
2024-07-12T11:27:33.393540209+08:00 stdout F   "domain": "data_prep",
2024-07-12T11:27:33.393543336+08:00 stdout F   "name": "psi",
2024-07-12T11:27:33.393546499+08:00 stdout F   "version": "0.0.5",
2024-07-12T11:27:33.393549363+08:00 stdout F   "attrPaths": [
2024-07-12T11:27:33.393552855+08:00 stdout F     "input/receiver_input/key",
2024-07-12T11:27:33.393555905+08:00 stdout F     "input/sender_input/key",
2024-07-12T11:27:33.393558928+08:00 stdout F     "protocol",
2024-07-12T11:27:33.393561766+08:00 stdout F     "sort_result",
2024-07-12T11:27:33.393564657+08:00 stdout F     "allow_duplicate_keys",
2024-07-12T11:27:33.393567896+08:00 stdout F     "allow_duplicate_keys/yes/join_type",
2024-07-12T11:27:33.393570723+08:00 stdout F     "fill_value_int",
2024-07-12T11:27:33.393598114+08:00 stdout F     "ecdh_curve"
2024-07-12T11:27:33.393601755+08:00 stdout F   ],
2024-07-12T11:27:33.393605016+08:00 stdout F   "attrs": [
2024-07-12T11:27:33.393608405+08:00 stdout F     {
2024-07-12T11:27:33.39361128+08:00 stdout F       "ss": [
2024-07-12T11:27:33.393614228+08:00 stdout F         "member_id2"
2024-07-12T11:27:33.393616949+08:00 stdout F       ]
2024-07-12T11:27:33.393619987+08:00 stdout F     },
2024-07-12T11:27:33.393623245+08:00 stdout F     {
2024-07-12T11:27:33.393626593+08:00 stdout F       "ss": [
2024-07-12T11:27:33.393629554+08:00 stdout F         "member_id"
2024-07-12T11:27:33.393632649+08:00 stdout F       ]
2024-07-12T11:27:33.393635372+08:00 stdout F     },
2024-07-12T11:27:33.393638372+08:00 stdout F     {
2024-07-12T11:27:33.393641386+08:00 stdout F       "s": "PROTOCOL_RR22"
2024-07-12T11:27:33.393644112+08:00 stdout F     },
2024-07-12T11:27:33.393647675+08:00 stdout F     {
2024-07-12T11:27:33.393650687+08:00 stdout F       "b": true
2024-07-12T11:27:33.393653688+08:00 stdout F     },
2024-07-12T11:27:33.393656558+08:00 stdout F     {
2024-07-12T11:27:33.393659415+08:00 stdout F       "s": "yes"
2024-07-12T11:27:33.393662414+08:00 stdout F     },
2024-07-12T11:27:33.393665174+08:00 stdout F     {
2024-07-12T11:27:33.393668171+08:00 stdout F       "s": "inner_join"
2024-07-12T11:27:33.393670978+08:00 stdout F     },
2024-07-12T11:27:33.39367395+08:00 stdout F     {
2024-07-12T11:27:33.39367675+08:00 stdout F       "isNa": true
2024-07-12T11:27:33.393682719+08:00 stdout F     },
2024-07-12T11:27:33.393685948+08:00 stdout F     {
2024-07-12T11:27:33.393689236+08:00 stdout F       "s": "CURVE_FOURQ"
2024-07-12T11:27:33.393692081+08:00 stdout F     }
2024-07-12T11:27:33.393694899+08:00 stdout F   ],
2024-07-12T11:27:33.393697781+08:00 stdout F   "inputs": [
2024-07-12T11:27:33.393700547+08:00 stdout F     {
2024-07-12T11:27:33.393703625+08:00 stdout F       "type": "sf.table.individual",
2024-07-12T11:27:33.393706572+08:00 stdout F       "meta": {
2024-07-12T11:27:33.393709731+08:00 stdout F         "@type": "type.googleapis.com/secretflow.spec.v1.IndividualTable",
2024-07-12T11:27:33.393712649+08:00 stdout F         "lineCount": "-1"
2024-07-12T11:27:33.393715516+08:00 stdout F       },
2024-07-12T11:27:33.393718406+08:00 stdout F       "dataRefs": [
2024-07-12T11:27:33.393721581+08:00 stdout F         {
2024-07-12T11:27:33.393725155+08:00 stdout F           "uri": "oss://***-algo-fra/dev/dmp/***/PrivacyComputing/PalmPayInstalledFeatures/yinyu/gaid_list.csv",
2024-07-12T11:27:33.393728047+08:00 stdout F           "party": "transsion",
2024-07-12T11:27:33.393731026+08:00 stdout F           "format": "csv"
2024-07-12T11:27:33.393733841+08:00 stdout F         }
2024-07-12T11:27:33.393736675+08:00 stdout F       ]
2024-07-12T11:27:33.393739558+08:00 stdout F     },
2024-07-12T11:27:33.393742301+08:00 stdout F     {
2024-07-12T11:27:33.393745469+08:00 stdout F       "type": "sf.table.individual",
2024-07-12T11:27:33.39374867+08:00 stdout F       "meta": {
2024-07-12T11:27:33.393751627+08:00 stdout F         "@type": "type.googleapis.com/secretflow.spec.v1.IndividualTable",
2024-07-12T11:27:33.393754505+08:00 stdout F         "lineCount": "-1"
2024-07-12T11:27:33.393757405+08:00 stdout F       },
2024-07-12T11:27:33.393760198+08:00 stdout F       "dataRefs": [
2024-07-12T11:27:33.393763079+08:00 stdout F         {
2024-07-12T11:27:33.393766239+08:00 stdout F           "uri": "train_data_0603_1159054923.csv",
2024-07-12T11:27:33.393769286+08:00 stdout F           "party": "palmpay",
2024-07-12T11:27:33.393772691+08:00 stdout F           "format": "csv"
2024-07-12T11:27:33.393775933+08:00 stdout F         }
2024-07-12T11:27:33.393779012+08:00 stdout F       ]
2024-07-12T11:27:33.393782074+08:00 stdout F     }
2024-07-12T11:27:33.393785271+08:00 stdout F   ],
2024-07-12T11:27:33.393788137+08:00 stdout F   "checkpointUri": "ckroqt-eowynlee-node-35-output-0"
2024-07-12T11:27:33.393791251+08:00 stdout F }
2024-07-12T11:27:33.398055205+08:00 stderr F Traceback (most recent call last):
2024-07-12T11:27:33.398069123+08:00 stderr F   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-07-12T11:27:33.398184289+08:00 stderr F     return _run_code(code, main_globals, None,
2024-07-12T11:27:33.398190707+08:00 stderr F   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
2024-07-12T11:27:33.39823252+08:00 stderr F     exec(code, run_globals)
2024-07-12T11:27:33.398237303+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py", line 547, in <module>
2024-07-12T11:27:33.398385524+08:00 stderr F     main()
2024-07-12T11:27:33.398391464+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
2024-07-12T11:27:33.398630871+08:00 stderr F     return self.main(*args, **kwargs)
2024-07-12T11:27:33.398639836+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
2024-07-12T11:27:33.398817077+08:00 stderr F     rv = self.invoke(ctx)
2024-07-12T11:27:33.398822677+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
2024-07-12T11:27:33.399076591+08:00 stderr F     return ctx.invoke(self.callback, **ctx.params)
2024-07-12T11:27:33.399088936+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
2024-07-12T11:27:33.399238053+08:00 stderr F     return __callback(*args, **kwargs)
2024-07-12T11:27:33.39924361+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py", line 514, in main
2024-07-12T11:27:33.399364985+08:00 stderr F     sf_node_eval_param = preprocess_sf_node_eval_param(
2024-07-12T11:27:33.399370515+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py", line 290, in preprocess_sf_node_eval_param
2024-07-12T11:27:33.399453766+08:00 stderr F     domaindata_id_to_dist_data(
2024-07-12T11:27:33.399458966+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py", line 149, in domaindata_id_to_dist_data
2024-07-12T11:27:33.399516264+08:00 stderr F     raise RuntimeError(
2024-07-12T11:27:33.399533108+08:00 stderr F RuntimeError: datasource_id of domain_data [crlpxwcb] is oss-5074fc04ed18e2078e07b55a8db5db0b, which doesn't match global datasource_id default-data-source
```

**Comment by zimu-yuxi** [comment]
确认下，transsion方是oss数据源，palmpay方是本地CSV吗？
另一方的日志有吗？

**Comment by john8628** [comment]
> 确认下，transsion方是oss数据源，palmpay方是本地CSV吗？ 另一方的日志有吗？

对的，另一侧没有明显错误日志
024-07-12T10:39:37.918112628+08:00 stdout F
2024-07-12T10:39:37.918115852+08:00 stdout F --
2024-07-12T10:39:37.918118818+08:00 stdout F
2024-07-12T10:39:37.91846398+08:00 stdout F 2024-07-12 02:39:37,918|palmpay|WARNING|secretflow|driver.py:init:442| When connecting to an existing cluster, num_cpus must not be provided. Num_cpus is neglected at this moment.
2024-07-12T10:39:37.918908195+08:00 stderr F 2024-07-12 02:39:37,918	INFO worker.py:1540 -- Connecting to existing Ray cluster at address: lnpy-kbxwquwv-node-35-0-global.palmpay.svc:23127...
2024-07-12T10:39:37.923618154+08:00 stdout F 2024-07-12 02:39:37,923|palmpay|DEBUG|secretflow|_api.py:acquire:331| Attempting to acquire lock 139801579058320 on /tmp/ray/session_2024-07-12_02-39-35_047517_42/node_ip_address.json.lock
2024-07-12T10:39:37.923735383+08:00 stdout F 2024-07-12 02:39:37,923|palmpay|DEBUG|secretflow|_api.py:acquire:334| Lock 139801579058320 acquired on /tmp/ray/session_2024-07-12_02-39-35_047517_42/node_ip_address.json.lock
2024-07-12T10:39:37.923869658+08:00 stdout F 2024-07-12 02:39:37,923|palmpay|DEBUG|secretflow|_api.py:release:364| Attempting to release lock 139801579058320 on /tmp/ray/session_2024-07-12_02-39-35_047517_42/node_ip_address.json.lock
2024-07-12T10:39:37.923907651+08:00 stdout F 2024-07-12 02:39:37,923|palmpay|DEBUG|secretflow|_api.py:release:367| Lock 139801579058320 released on /tmp/ray/session_2024-07-12_02-39-35_047517_42/node_ip_address.json.lock
2024-07-12T10:39:37.925926849+08:00 stdout F 2024-07-12 02:39:37,925|palmpay|DEBUG|secretflow|_api.py:acquire:331| Attempting to acquire lock 139801579058224 on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.926097806+08:00 stdout F 2024-07-12 02:39:37,926|palmpay|DEBUG|secretflow|_api.py:acquire:334| Lock 139801579058224 acquired on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.926252241+08:00 stdout F 2024-07-12 02:39:37,926|palmpay|DEBUG|secretflow|_api.py:release:364| Attempting to release lock 139801579058224 on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.926304647+08:00 stdout F 2024-07-12 02:39:37,926|palmpay|DEBUG|secretflow|_api.py:release:367| Lock 139801579058224 released on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.926444085+08:00 stdout F 2024-07-12 02:39:37,926|palmpay|DEBUG|secretflow|_api.py:acquire:331| Attempting to acquire lock 139801579058464 on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.926590661+08:00 stdout F 2024-07-12 02:39:37,926|palmpay|DEBUG|secretflow|_api.py:acquire:334| Lock 139801579058464 acquired on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.926705139+08:00 stdout F 2024-07-12 02:39:37,926|palmpay|DEBUG|secretflow|_api.py:release:364| Attempting to release lock 139801579058464 on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.926729864+08:00 stdout F 2024-07-12 02:39:37,926|palmpay|DEBUG|secretflow|_api.py:release:367| Lock 139801579058464 released on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.92687715+08:00 stdout F 2024-07-12 02:39:37,926|palmpay|DEBUG|secretflow|_api.py:acquire:331| Attempting to acquire lock 139801579058224 on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.927014437+08:00 stdout F 2024-07-12 02:39:37,926|palmpay|DEBUG|secretflow|_api.py:acquire:334| Lock 139801579058224 acquired on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.927124729+08:00 stdout F 2024-07-12 02:39:37,927|palmpay|DEBUG|secretflow|_api.py:release:364| Attempting to release lock 139801579058224 on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.92715445+08:00 stdout F 2024-07-12 02:39:37,927|palmpay|DEBUG|secretflow|_api.py:release:367| Lock 139801579058224 released on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.927302643+08:00 stdout F 2024-07-12 02:39:37,927|palmpay|DEBUG|secretflow|_api.py:acquire:331| Attempting to acquire lock 139801579058464 on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.927447084+08:00 stdout F 2024-07-12 02:39:37,927|palmpay|DEBUG|secretflow|_api.py:acquire:334| Lock 139801579058464 acquired on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.927538416+08:00 stdout F 2024-07-12 02:39:37,927|palmpay|DEBUG|secretflow|_api.py:release:364| Attempting to release lock 139801579058464 on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.927561885+08:00 stdout F 2024-07-12 02:39:37,927|palmpay|DEBUG|secretflow|_api.py:release:367| Lock 139801579058464 released on /tmp/ray/session_2024-07-12_02-39-35_047517_42/ports_by_node.json.lock
2024-07-12T10:39:37.92767774+08:00 stderr F 2024-07-12 02:39:37,927	INFO worker.py:1724 -- Connected to Ray cluster.
2024-07-12T10:39:38.656389518+08:00 stderr F *** SIGTERM received at time=1720751978 on cpu 5 ***
2024-07-12T10:39:38.659759581+08:00 stderr F PC: @     0x7f267d811d26  (unknown)  recv
2024-07-12T10:39:38.659801094+08:00 stderr F     @     0x7f267d812ce0  (unknown)  (unknown)
2024-07-12T10:39:38.659870174+08:00 stderr F [2024-07-12 02:39:38,659 E 7 7] logging.cc:361: *** SIGTERM received at time=1720751978 on cpu 5 ***
2024-07-12T10:39:38.659886596+08:00 stderr F [2024-07-12 02:39:38,659 E 7 7] logging.cc:361: PC: @     0x7f267d811d26  (unknown)  recv
2024-07-12T10:39:38.659960376+08:00 stderr F [2024-07-12 02:39:38,659 E 7 7] logging.cc:361:     @     0x7f267d812ce0  (unknown)  (unknown)

**Comment by zimu-yuxi** [comment]
1.可以查下secretpad的元数据，sqlite在app/db/secretpad.sqlite
2.kuscia容器内kubectl get domaindata crlpxwcb -o yaml -n transsion

**Comment by john8628** [comment]
`
[root@root-kuscia-autonomy-transsion-vm-0-2-centos kuscia]# kubectl get domaindata crlpxwcb -o yaml -n transsion
apiVersion: kuscia.secretflow/v1alpha1
kind: DomainData
metadata:
  annotations:
    kuscia.secretflow/initiator: transsion
  creationTimestamp: "2024-07-12T03:25:42Z"
  generation: 1
  labels:
    kuscia.secretflow/domaindata-type: table
    kuscia.secretflow/domaindata-vendor: manual
    kuscia.secretflow/interconn-protocol-type: kuscia
  name: crlpxwcb
  namespace: transsion
  resourceVersion: "1055055"
  uid: 78194529-de96-42dc-8d8a-f235891b3df6
spec:
  attributes:
    DatasourceName: transsion_user
    DatasourceType: OSS
    description: ""
  author: transsion
  columns:
  - comment: ""
    name: member_id2
    type: str
  - comment: ""
    name: gaid
    type: int
  - comment: ""
    name: gender
    type: int
  dataSource: oss-5074fc04ed18e2078e07b55a8db5db0b
  fileFormat: unknown
  name: test_oss_2
  relativeURI: oss://***/dev/dmp/**/PrivacyComputing/PalmPayInstalledFeatures/yinyu/gaid_list.csv
  type: table
  vendor: manual
`

**Comment by zimu-yuxi** [comment]
根据报错信息，看像是任务的sf_node_eval_param传参有问题

**Comment by john8628** [comment]
已经通过更新project_graph_domain_datasource的表数据，更新数据源信息，修正此问题，感谢 @zimu-yuxi
