### ISSUE TITLE
想要在window上实现开发和个性化改造的问题

### ISSUE THREAD

**Issue by ShaneGu4Real** [secretflow/secretpad#115]
### Issue Type

Feature

### Have you searched for existing issues?

Yes

### Question Details

```shell
您好，看文档中写目前只本地调试（目前只针对 MAC），是否意思是我们没法在Windows环境上，部署secretpad前后端的开发环境了，如果我们只是想在secretpad里增加前端界面，增加一些个性化的界面功能，后端增加api接口处理，不涉及到kuscia调度和隐私计算相关的部分，如果可以是不是可以屏蔽一些代码，实现在本地Windows环境上进行开发调试？如果可以应该怎么做，烦请解答下，谢谢。
```

**Comment by BrainWH** [comment]
你好，因为secretpad的启动需要依赖kuscia容器，所以需要下载allinone包部署kuscia容器进行本地调试，在windows上可以借助WSL2进行部署，然后按照[本地调试文档]([https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.9.0b0/development/ru_in_idea_cn)](https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.9.0b0/development/ru_in_idea_cn)%E8%B7%91%E4%B8%80%E4%B8%8B)，但是目前没有针对windows做本地调试的测试

**Comment by ShaneGu4Real** [comment]
1，你好，我在windows上通过wsl2部署了mvp，参考官网的教程，关闭了secrepad容器，拉取了master的代码，通过windows的idea进行启动但是报的错误如下：
024-08-16T21:56:22.390+08:00 ERROR 32616 --- [           main] o.s.s.k.v.i.KusciaGrpcLoggingInterceptor : [kuscia] kuscia-system Cancel request: null

io.grpc.StatusRuntimeException: UNAVAILABLE: Unable to resolve host root-kuscia-master
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
	at org.secretflow.v1alpha1.kusciaapi.DomainServiceGrpc$DomainServiceBlockingStub.queryDomain(DomainServiceGrpc.java:351)
	at org.secretflow.secretpad.kuscia.v1alpha1.service.impl.KusciaGrpcClientAdapter.queryDomain(KusciaGrpcClientAdapter.java:285)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at org.secretflow.secretpad.kuscia.v1alpha1.aspect.KusciaApiServiceAspect.aroundServiceMethod(KusciaApiServiceAspect.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
	at org.secretflow.secretpad.kuscia.v1alpha1.service.impl.KusciaGrpcClientAdapter$$SpringCGLIB$$0.queryDomain(<generated>)
	at org.secretflow.secretpad.web.init.TeeResourceInit.initTeeNodeInKuscia(TeeResourceInit.java:105)
	at org.secretflow.secretpad.web.init.TeeResourceInit.run(TeeResourceInit.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
我修改了application-dev.yaml里的端口也不行，麻烦看下应该怎么解决这个错误呢，下面是我启动的容器信息
![image](https://github.com/user-attachments/assets/8e7c14ad-2f54-4f10-aafb-f9c80666a057)

下面是application-dev.yaml
![image](https://github.com/user-attachments/assets/3a1b8811-4104-4373-be52-14c270feb82d)

2，另外咨询下，还需要参考旧版本教程进行数据库、证书之类配置（示例：sqlite）吗，因为我看到新版本的部署教程和旧的有些差别

**Comment by ShaneGu4Real** [comment]
您好，
1，您可以看我附带的容器启动截图,root-kuscia-master是可以启动的，我在wsl2里正常启动了mvp，本地可以登录secretpad界面，我按照新版本教程里，把secretpad的镜像停止了，root-kuscia-master还是正常启动的，猜测是哪里配置的问题导致无法访问root-kuscia-master，麻烦能否参考上面回答截图报错信息，帮着排查下是哪里无法连接root-kuscia-master
2，我看新版本的教程里没有数据库、证书之类配置（示例：sqlite），旧版本里有，我理解的意思是新版本不需要配置证书、数据库之类的了吗

**Comment by wangzul** [comment]
> 1，你好，我在windows上通过wsl2部署了mvp，参考官网的教程，关闭了secrepad容器，拉取了master的代码，通过windows的idea进行启动但是报的错误如下： 024-08-16T21:56:22.390+08:00 ERROR 32616 --- [ main] o.s.s.k.v.i.KusciaGrpcLoggingInterceptor : [kuscia] kuscia-system Cancel request: null
> 
> io.grpc.StatusRuntimeException: UNAVAILABLE: Unable to resolve host root-kuscia-master at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268) at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249) at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167) at org.secretflow.v1alpha1.kusciaapi.DomainServiceGrpc$DomainServiceBlockingStub.queryDomain(DomainServiceGrpc.java:351) at org.secretflow.secretpad.kuscia.v1alpha1.service.impl.KusciaGrpcClientAdapter.queryDomain(KusciaGrpcClientAdapter.java:285) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) at org.secretflow.secretpad.kuscia.v1alpha1.aspect.KusciaApiServiceAspect.aroundServiceMethod(KusciaApiServiceAspect.java:53) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637) at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627) at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703) at org.secretflow.secretpad.kuscia.v1alpha1.service.impl.KusciaGrpcClientAdapter$$SpringCGLIB$$0.queryDomain() at org.secretflow.secretpad.web.init.TeeResourceInit.initTeeNodeInKuscia(TeeResourceInit.java:105) at org.secretflow.secretpad.web.init.TeeResourceInit.run(TeeResourceInit.java:83) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) 我修改了application-dev.yaml里的端口也不行，麻烦看下应该怎么解决这个错误呢，下面是我启动的容器信息 ![image](https://private-user-images.githubusercontent.com/85916085/358610456-8e7c14ad-2f54-4f10-aafb-f9c80666a057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjAzMjMsIm5iZiI6MTcyNDEyMDAyMywicGF0aCI6Ii84NTkxNjA4NS8zNTg2MTA0NTYtOGU3YzE0YWQtMmY1NC00ZjEwLWFhZmItZjljODA2NjZhMDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDAyMTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYjhlMjQxNjIwZDdiZTVmMDAyZTA0ZWMwODMzNTFiYzdmYWZhNGI5ZmY2YzQ2NmI4ZjJlZWMzNzliZmRjMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sh7KpnpDCnP-DX0440vYS9KTkQopf4KIpHAf0vz9EtQ)
> 
> 下面是application-dev.yaml ![image](https://private-user-images.githubusercontent.com/85916085/358610335-3a1b8811-4104-4373-be52-14c270feb82d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjAzMjMsIm5iZiI6MTcyNDEyMDAyMywicGF0aCI6Ii84NTkxNjA4NS8zNTg2MTAzMzUtM2ExYjg4MTEtNDEwNC00MzczLWJlNTItMTRjMjcwZmViODJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDAyMTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZTEyYjIxNWQ1ZjRlM2EyMDAxZmJlODRjNjQxYzNlOTEzNjhkZDgzODJmYWJmMGU2ZjlhM2RjZGQxZTJkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H5IhV53w1fmY1YzqE4XCA12jnJHJFog5YNoWeYQu6As)
> 
> 2，另外咨询下，还需要参考旧版本教程进行数据库、证书之类配置（示例：sqlite）吗，因为我看到新版本的部署教程和旧的有些差别

我需要提供一下其他配置
1. docker network inspect kuscia-exchange 
2. 提供一下完整的application-dev.yaml

**Comment by ShaneGu4Real** [comment]
> > 1，你好，我在windows上通过wsl2部署了mvp，参考官网的教程，关闭了secrepad容器，拉取了master的代码，通过windows的idea进行启动但是报的错误如下： 024-08-16T21:56:22.390+08:00 ERROR 32616 --- [ main] o.s.s.k.v.i.KusciaGrpcLoggingInterceptor : [kuscia] kuscia-system Cancel request: null
> > io.grpc.StatusRuntimeException: UNAVAILABLE: Unable to resolve host root-kuscia-master at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268) at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249) at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167) at org.secretflow.v1alpha1.kusciaapi.DomainServiceGrpc$DomainServiceBlockingStub.queryDomain(DomainServiceGrpc.java:351) at org.secretflow.secretpad.kuscia.v1alpha1.service.impl.KusciaGrpcClientAdapter.queryDomain(KusciaGrpcClientAdapter.java:285) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) at org.secretflow.secretpad.kuscia.v1alpha1.aspect.KusciaApiServiceAspect.aroundServiceMethod(KusciaApiServiceAspect.java:53) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637) at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627) at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703) at org.secretflow.secretpad.kuscia.v1alpha1.service.impl.KusciaGrpcClientAdapter$$SpringCGLIB$$0.queryDomain() at org.secretflow.secretpad.web.init.TeeResourceInit.initTeeNodeInKuscia(TeeResourceInit.java:105) at org.secretflow.secretpad.web.init.TeeResourceInit.run(TeeResourceInit.java:83) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) 我修改了application-dev.yaml里的端口也不行，麻烦看下应该怎么解决这个错误呢，下面是我启动的容器信息 ![image](https://private-user-images.githubusercontent.com/85916085/358610456-8e7c14ad-2f54-4f10-aafb-f9c80666a057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjAzMjMsIm5iZiI6MTcyNDEyMDAyMywicGF0aCI6Ii84NTkxNjA4NS8zNTg2MTA0NTYtOGU3YzE0YWQtMmY1NC00ZjEwLWFhZmItZjljODA2NjZhMDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDAyMTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYjhlMjQxNjIwZDdiZTVmMDAyZTA0ZWMwODMzNTFiYzdmYWZhNGI5ZmY2YzQ2NmI4ZjJlZWMzNzliZmRjMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sh7KpnpDCnP-DX0440vYS9KTkQopf4KIpHAf0vz9EtQ)
> > 下面是application-dev.yaml ![image](https://private-user-images.githubusercontent.com/85916085/358610335-3a1b8811-4104-4373-be52-14c270feb82d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjAzMjMsIm5iZiI6MTcyNDEyMDAyMywicGF0aCI6Ii84NTkxNjA4NS8zNTg2MTAzMzUtM2ExYjg4MTEtNDEwNC00MzczLWJlNTItMTRjMjcwZmViODJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDAyMTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZTEyYjIxNWQ1ZjRlM2EyMDAxZmJlODRjNjQxYzNlOTEzNjhkZDgzODJmYWJmMGU2ZjlhM2RjZGQxZTJkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H5IhV53w1fmY1YzqE4XCA12jnJHJFog5YNoWeYQu6As)
> > 2，另外咨询下，还需要参考旧版本教程进行数据库、证书之类配置（示例：sqlite）吗，因为我看到新版本的部署教程和旧的有些差别
> 
> 我需要提供一下其他配置
> 
> 1. docker network inspect kuscia-exchange
> 2. 提供一下完整的application-dev.yaml

@wangzul 您好，信息如下，mac地址、等信息做了涂改，这个需要注意
1,docker network inspect kuscia-exchange
[
    {
        "Name": "kuscia-exchange",
        "Id": "7e6c43394333dd8b7827b3f360ea5a0a3eb78938876649a9c12",
        "Created": "2024-08-15T07:56:53.3316272Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "152.12.0.0/16",
                    "Gateway": "152.12.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "934a67deac11076cfdd84203f6cb73a356f55234630e74d952ff08539": {
                "Name": "root-kuscia-lite-bob",
                "EndpointID": "3a485777454b0c322edce6aac93e66461a128474f1f6deba0a8dd34a1d43f259",
                "MacAddress": "12:42:de:12:00:12",
                "IPv4Address": "152.12.0.2/16",
                "IPv6Address": ""
            },
            "a19ca10d59cb6febc49fbef4ce90fea1041d19379bf89eb369aee85b": {
                "Name": "root-kuscia-lite-alice",
                "EndpointID": "810d6547c4713bf0ff5701238d6d0fa0d04e4d3fea1cdd5cda8fcff6c878ba59",
                "MdeAddress": "12:42:de:12:00:04",
                "IPv4Address": "152.12.0.4/16",
                "IPv6Address": ""
            },
            "ae3125d350165d5c33fce4df6d9d5b93d1ec81fc00c32b262935dc9": {
                "Name": "root-kuscia-master",
                "EndpointID": "0f5e17da386c56ceb85df24d1ffffc31cd1156b9609f9b550f473a9540f6b694",
                "MdeAddress": "12:42:de:12:00:06",
                "IPv4Address": "152.12.0.6/16",
                "IPv6Address": ""
            },
            "f55da06527712fd58566a855a1214a1d7548e60cc15389a666": {
                "Name": "root-kuscia-lite-tee",
                "EndpointID": "de8b66c6eb3976c46d4c721e9edf8b815d012dbe85ed415ff849c38f49bf1051",
                "MdeAddress": "12:42:de:12:00:05",
                "IPv4Address": "152.12.0.5/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
2,完整的application-dev.yaml就是下载的git上master的内容，没做变化，内容如下：
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:sqlite:./db/secretpad.sqlite

springdoc:
  api-docs:
    enabled: true

secretpad:
  platform-type: CENTER    # CENTER  EDGE  AUTONOMY
  deploy-mode: ${DEPLOY_MODE:ALL-IN-ONE} # MPC TEE ALL-IN-ONE
  node-id: ${NODE_ID:kuscia-system} # install.sh -n
  gateway: ${KUSCIA_GW_ADDRESS:127.0.0.1:18301} # install.sh -q envoy port (used in autonomy or master or edge mode)
  logs:
    path: ../log

kuscia:
  nodes:
    - domainId: ${NODE_ID:kuscia-system}
      mode: master
      host: ${KUSCIA_API_ADDRESS:root-kuscia-master}
      port: ${KUSCIA_API_PORT:8083}
      protocol: ${KUSCIA_PROTOCOL:tls}
      cert-file: config/certs/client.crt
      key-file: config/certs/client.pem
      token: config/certs/token

    - domainId: alice
      mode: lite
      host: ${KUSCIA_API_LITE_ALICE_ADDRESS:root-kuscia-lite-alice}
      port: ${KUSCIA_API_PORT:8083}
      protocol: ${KUSCIA_PROTOCOL:tls}
      cert-file: config/certs/alice/client.crt
      key-file: config/certs/alice/client.pem
      token: config/certs/alice/token

    - domainId: bob
      mode: lite
      host: ${KUSCIA_API_LITE_BOB_ADDRESS:root-kuscia-lite-bob}
      port: ${KUSCIA_API_PORT:8083}
      protocol: ${KUSCIA_PROTOCOL:tls}
      cert-file: config/certs/bob/client.crt
      key-file: config/certs/bob/client.pem
      token: config/certs/bob/token

另外有微信、qq群其他的联系方式，可以私信我吗，通过提issue方式解决，效率有点慢，谢谢！

**Comment by ShaneGu4Real** [comment]
@wangzul 您好，麻烦看下，谢谢

**Comment by wangzul** [comment]
> @wangzul 您好，麻烦看下，谢谢

问题分析

1. kuscia 是在wsl2安装的，但是SecretPad是通过本机进行调试的。
2. allinone 相关容器统一使用相同docker network配置，默认是可以通过容器名称互相访问。

pad调试错误信息：Unable to resolve host root-kuscia-master at 
因此可以通过修改pad配置文件中所有域名解析的配置，更改为本机链接wsl2的ip+端口进行访问
wsl2 IP可在wsl2 内部使用ifconfig | grep eth0 查看

**Comment by ShaneGu4Real** [comment]
感谢，问题解决了，多谢
