### ISSUE TITLE
本地调试问题

### ISSUE THREAD

**Issue by nottogoby** [secretflow/secretpad#119]
### 文档修改建议

下载main的MVP
以中心化的模式安装 bash install.sh master -P notls
Probe secretpad in container 'kuscia-master-secretpad' failed. Please check the log

Caused by: java.io.FileNotFoundException: config/certs/alice/token
	at org.secretflow.secretpad.common.util.FileUtils.readFile(FileUtils.java:51)
	at org.secretflow.secretpad.common.util.FileUtils.readFile2String(FileUtils.java:64)
	at org.secretflow.v1alpha1.factory.embedded.EmbeddedNodeKusciaApiChannelFactory.newClientChannel(EmbeddedNodeKusciaApiChannelFactory.java:91)
	...

![QQ_1723803892288](https://github.com/user-attachments/assets/3e8469d5-06e9-4ee5-b827-7ceea917717a)

<details>
      <summary>技术信息</summary>
      <ul>
        <li>页面 <a href="https://www.secretflow.org.cn/zh-CN/docs/secretpad/main/development/ru_in_idea_cn">https://www.secretflow.org.cn/zh-CN/docs/secretpad/main/development/ru_in_idea_cn</a></li>
        <li>源码 <a href="https://github.com/secretflow/secretpad/tree/42cdb3c48741eb3041df7692a798ec1b85646203/docs/development/ru_in_idea_cn.md">https://github.com/secretflow/secretpad/tree/42cdb3c48741eb3041df7692a798ec1b85646203/docs/development/ru_in_idea_cn.md</a></li>
        <li>浏览器 <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36</code></li>
      </ul>
    </details>

**Comment by wangzul** [comment]
可以详细说一下你的执行流程吗？
我本地复现了一些下面是执行详细信息与你描述的不相同，不理解文档修改指的是？
![image](https://github.com/user-attachments/assets/588e4cd8-51f6-4589-b958-7176a8395410)

**Comment by wangzul** [comment]
是指mvp包的链接吗？
![image](https://github.com/user-attachments/assets/5e34891b-068b-4150-ab95-6939cfb27655)

**Comment by nottogoby** [comment]
> 是指mvp包的链接吗？ ![image](https://private-user-images.githubusercontent.com/55971198/358574634-5e34891b-068b-4150-ab95-6939cfb27655.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzY3NDIsIm5iZiI6MTcyNDAzNjQ0MiwicGF0aCI6Ii81NTk3MTE5OC8zNTg1NzQ2MzQtNWUzNDg5MWItMDY4Yi00MTUwLWFiOTUtNjkzOWNmYjI3NjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAzMDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0OTRhNmVjNzRhYWQxYWNjZDg3M2IzMjNiYTU5ZjI2YjIwMjc2M2UyNTI4M2Y4Y2JmMTJjMjcxMGJkYmM3OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YmzEYX36vgY4D5TXnIXFqtCyeAq3dHHTY7bG3wWOFHY)

本机下载这个Mvp包后执行tar -zxvf 解压。然后bash install.sh master -P notls 中心化部署。就会出现java.io.FileNotFoundException: config/certs/alice/token

**Comment by wangzul** [comment]
> > 是指mvp包的链接吗？ ![image](https://private-user-images.githubusercontent.com/55971198/358574634-5e34891b-068b-4150-ab95-6939cfb27655.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzY3NDIsIm5iZiI6MTcyNDAzNjQ0MiwicGF0aCI6Ii81NTk3MTE5OC8zNTg1NzQ2MzQtNWUzNDg5MWItMDY4Yi00MTUwLWFiOTUtNjkzOWNmYjI3NjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAzMDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0OTRhNmVjNzRhYWQxYWNjZDg3M2IzMjNiYTU5ZjI2YjIwMjc2M2UyNTI4M2Y4Y2JmMTJjMjcxMGJkYmM3OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YmzEYX36vgY4D5TXnIXFqtCyeAq3dHHTY7bG3wWOFHY)
> 
> 本机下载这个Mvp包后执行tar -zxvf 解压。然后bash install.sh master -P notls 中心化部署。就会出现java.io.FileNotFoundException: config/certs/alice/token

好的，这个问题已经反馈过了后面的版本会进行修复，你可以从allinone中拉取https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.8.0b0/deployment_package
