### ISSUE TITLE
secretpad 隐私求交报错

### ISSUE THREAD

**Issue by 123zzc** [secretflow/secretpad#151]
### Issue Type

Install/Deploy

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

centos

### All_in_one Version

0.6.0

### Module type

secretflow

### Module version

0.6.0

### What happend and What you expected to happen.

```shell
本地启动secretpad调用远程kuscia，进行隐私求交时报错。

kuscia容器中：/home/var/stdout 目录下完整job日志如下：
```

### Log output.

```shell
024-10-10T11:54:02.01261381+08:00 stderr F WARNING:root:Since the GPL-licensed package `unidecode` is not installed, using Python's `unicodedata` package which yields worse results.
2024-10-10T11:54:04.291513209+08:00 stdout F 2024-10-10 03:54:04,291|rxf|INFO|secretflow|entry.py:start_ray:59| ray_conf: RayConfig(ray_node_ip_address='twqb-gaexmzjp-node-35-0-global.rxf.svc', ray_node_manager_port=30867, ray_object_manager_port=30868, ray_client_server_port=30869, ray_worker_ports=[], ray_gcs_port=30866)
2024-10-10T11:54:04.291543703+08:00 stdout F 2024-10-10 03:54:04,291|rxf|INFO|secretflow|entry.py:start_ray:67| Trying to start ray head node at twqb-gaexmzjp-node-35-0-global.rxf.svc, start command: ray start --head --include-dashboard=false --disable-usage-stats --num-cpus=32 --node-ip-address=twqb-gaexmzjp-node-35-0-global.rxf.svc --port=30866 --node-manager-port=30867 --object-manager-port=30868 --ray-client-server-port=30869
2024-10-10T11:54:06.843629759+08:00 stdout F 2024-10-10 03:54:06,843|rxf|INFO|secretflow|entry.py:start_ray:80| 2024-10-10 03:54:04,845 INFO usage_lib.py:423 -- Usage stats collection is disabled.
2024-10-10T11:54:06.84364951+08:00 stdout F 2024-10-10 03:54:04,845     INFO scripts.py:744 -- Local node IP: twqb-gaexmzjp-node-35-0-global.rxf.svc
2024-10-10T11:54:06.843653235+08:00 stdout F 2024-10-10 03:54:06,734    SUCC scripts.py:781 -- --------------------
2024-10-10T11:54:06.843655985+08:00 stdout F 2024-10-10 03:54:06,734    SUCC scripts.py:782 -- Ray runtime started.
2024-10-10T11:54:06.843658639+08:00 stdout F 2024-10-10 03:54:06,734    SUCC scripts.py:783 -- --------------------
2024-10-10T11:54:06.84366162+08:00 stdout F 2024-10-10 03:54:06,734     INFO scripts.py:785 -- Next steps
2024-10-10T11:54:06.843665004+08:00 stdout F 2024-10-10 03:54:06,734    INFO scripts.py:788 -- To add another node to this Ray cluster, run
2024-10-10T11:54:06.843667755+08:00 stdout F 2024-10-10 03:54:06,735    INFO scripts.py:791 --   ray start --address='twqb-gaexmzjp-node-35-0-global.rxf.svc:30866'
2024-10-10T11:54:06.843670287+08:00 stdout F 2024-10-10 03:54:06,735    INFO scripts.py:800 -- To connect to this Ray cluster:
2024-10-10T11:54:06.843672816+08:00 stdout F 2024-10-10 03:54:06,735    INFO scripts.py:802 -- import ray
2024-10-10T11:54:06.843675447+08:00 stdout F 2024-10-10 03:54:06,735    INFO scripts.py:803 -- ray.init(_node_ip_address='twqb-gaexmzjp-node-35-0-global.rxf.svc')
2024-10-10T11:54:06.843677931+08:00 stdout F 2024-10-10 03:54:06,735    INFO scripts.py:834 -- To terminate the Ray runtime, run
2024-10-10T11:54:06.843680642+08:00 stdout F 2024-10-10 03:54:06,735    INFO scripts.py:835 --   ray stop
2024-10-10T11:54:06.843683091+08:00 stdout F 2024-10-10 03:54:06,735    INFO scripts.py:838 -- To view the status of the cluster, use
2024-10-10T11:54:06.843685497+08:00 stdout F 2024-10-10 03:54:06,735    INFO scripts.py:839 --   ray status
2024-10-10T11:54:06.843687996+08:00 stdout F
2024-10-10T11:54:06.843694937+08:00 stdout F 2024-10-10 03:54:06,843|rxf|INFO|secretflow|entry.py:start_ray:81| Succeeded to start ray head node at twqb-gaexmzjp-node-35-0-global.rxf.svc.
2024-10-10T11:54:06.844301236+08:00 stdout F 2024-10-10 03:54:06,844|rxf|INFO|secretflow|entry.py:main:510| datasource.access_directly False
2024-10-10T11:54:06.84431774+08:00 stdout F sf_node_eval_param  {
2024-10-10T11:54:06.844321603+08:00 stdout F   "domain": "data_prep",
2024-10-10T11:54:06.844325368+08:00 stdout F   "name": "psi",
2024-10-10T11:54:06.844328796+08:00 stdout F   "version": "0.0.7",
2024-10-10T11:54:06.844332533+08:00 stdout F   "attrPaths": [
2024-10-10T11:54:06.84433684+08:00 stdout F     "input/input_table_1/key",
2024-10-10T11:54:06.844340324+08:00 stdout F     "input/input_table_2/key",
2024-10-10T11:54:06.844343619+08:00 stdout F     "protocol",
2024-10-10T11:54:06.844346992+08:00 stdout F     "sort_result",
2024-10-10T11:54:06.844350323+08:00 stdout F     "allow_duplicate_keys",
2024-10-10T11:54:06.844354367+08:00 stdout F     "allow_duplicate_keys/no/skip_duplicates_check",
2024-10-10T11:54:06.844358166+08:00 stdout F     "allow_duplicate_keys/no/receiver_parties",
2024-10-10T11:54:06.8443721+08:00 stdout F     "ecdh_curve"
2024-10-10T11:54:06.844376034+08:00 stdout F   ],
2024-10-10T11:54:06.844380051+08:00 stdout F   "attrs": [
2024-10-10T11:54:06.844383541+08:00 stdout F     {
2024-10-10T11:54:06.844387446+08:00 stdout F       "ss": [
2024-10-10T11:54:06.844390672+08:00 stdout F         "id1"
2024-10-10T11:54:06.844394003+08:00 stdout F       ]
2024-10-10T11:54:06.844397182+08:00 stdout F     },
2024-10-10T11:54:06.844400098+08:00 stdout F     {
2024-10-10T11:54:06.844403427+08:00 stdout F       "ss": [
2024-10-10T11:54:06.844406679+08:00 stdout F         "id2"
2024-10-10T11:54:06.844409932+08:00 stdout F       ]
2024-10-10T11:54:06.844413593+08:00 stdout F     },
2024-10-10T11:54:06.844417719+08:00 stdout F     {
2024-10-10T11:54:06.844421721+08:00 stdout F       "s": "PROTOCOL_RR22"
2024-10-10T11:54:06.844425251+08:00 stdout F     },
2024-10-10T11:54:06.844428598+08:00 stdout F     {
2024-10-10T11:54:06.844432029+08:00 stdout F       "b": true
2024-10-10T11:54:06.844435531+08:00 stdout F     },
2024-10-10T11:54:06.844439436+08:00 stdout F     {
2024-10-10T11:54:06.844442684+08:00 stdout F       "s": "no"
2024-10-10T11:54:06.844446012+08:00 stdout F     },
2024-10-10T11:54:06.844449463+08:00 stdout F     {
2024-10-10T11:54:06.844452711+08:00 stdout F       "isNa": true
2024-10-10T11:54:06.84445594+08:00 stdout F     },
2024-10-10T11:54:06.844459439+08:00 stdout F     {
2024-10-10T11:54:06.844462632+08:00 stdout F       "ss": [
2024-10-10T11:54:06.844465988+08:00 stdout F         "rxf"
2024-10-10T11:54:06.844469381+08:00 stdout F       ]
2024-10-10T11:54:06.844472584+08:00 stdout F     },
2024-10-10T11:54:06.844475948+08:00 stdout F     {
2024-10-10T11:54:06.844479014+08:00 stdout F       "s": "CURVE_FOURQ"
2024-10-10T11:54:06.844482451+08:00 stdout F     }
2024-10-10T11:54:06.844485957+08:00 stdout F   ],
2024-10-10T11:54:06.844489197+08:00 stdout F   "inputs": [
2024-10-10T11:54:06.844492635+08:00 stdout F     {
2024-10-10T11:54:06.844496154+08:00 stdout F       "type": "sf.table.individual",
2024-10-10T11:54:06.844499464+08:00 stdout F       "meta": {
2024-10-10T11:54:06.844503445+08:00 stdout F         "@type": "type.googleapis.com/secretflow.spec.v1.IndividualTable",
2024-10-10T11:54:06.844507099+08:00 stdout F         "lineCount": "-1"
2024-10-10T11:54:06.844510478+08:00 stdout F       },
2024-10-10T11:54:06.844514133+08:00 stdout F       "dataRefs": [
2024-10-10T11:54:06.844517477+08:00 stdout F         {
2024-10-10T11:54:06.844520953+08:00 stdout F           "uri": "alice_919413449.csv",
2024-10-10T11:54:06.844524619+08:00 stdout F           "party": "rxf",
2024-10-10T11:54:06.844528298+08:00 stdout F           "format": "csv"
2024-10-10T11:54:06.844531448+08:00 stdout F         }
2024-10-10T11:54:06.844534797+08:00 stdout F       ]
2024-10-10T11:54:06.844538051+08:00 stdout F     },
2024-10-10T11:54:06.84454148+08:00 stdout F     {
2024-10-10T11:54:06.844545007+08:00 stdout F       "type": "sf.table.individual",
2024-10-10T11:54:06.844548387+08:00 stdout F       "meta": {
2024-10-10T11:54:06.844551933+08:00 stdout F         "@type": "type.googleapis.com/secretflow.spec.v1.IndividualTable",
2024-10-10T11:54:06.844555363+08:00 stdout F         "lineCount": "-1"
2024-10-10T11:54:06.844559212+08:00 stdout F       },
2024-10-10T11:54:06.844562823+08:00 stdout F       "dataRefs": [
2024-10-10T11:54:06.844566324+08:00 stdout F         {
2024-10-10T11:54:06.844569418+08:00 stdout F           "uri": "bob_1757101951.csv",
2024-10-10T11:54:06.844572607+08:00 stdout F           "party": "zhaohang2",
2024-10-10T11:54:06.84457595+08:00 stdout F           "format": "csv"
2024-10-10T11:54:06.844579607+08:00 stdout F         }
2024-10-10T11:54:06.844583003+08:00 stdout F       ]
2024-10-10T11:54:06.844586641+08:00 stdout F     }
2024-10-10T11:54:06.844590156+08:00 stdout F   ],
2024-10-10T11:54:06.844593768+08:00 stdout F   "checkpointUri": "cktwqb-gaexmzjp-node-35-output-0"
2024-10-10T11:54:06.844597574+08:00 stdout F }
2024-10-10T11:54:06.844619855+08:00 stderr F Traceback (most recent call last):
2024-10-10T11:54:06.844634284+08:00 stderr F   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-10-10T11:54:06.845597142+08:00 stderr F     return _run_code(code, main_globals, None,
2024-10-10T11:54:06.845608799+08:00 stderr F   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
2024-10-10T11:54:06.845612023+08:00 stderr F     exec(code, run_globals)
2024-10-10T11:54:06.845615012+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py", line 547, in <module>
2024-10-10T11:54:06.845688951+08:00 stderr F     main()
2024-10-10T11:54:06.84569261+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
2024-10-10T11:54:06.84769107+08:00 stderr F     return self.main(*args, **kwargs)
2024-10-10T11:54:06.84769708+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
2024-10-10T11:54:06.847831166+08:00 stderr F     rv = self.invoke(ctx)
2024-10-10T11:54:06.847834472+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
2024-10-10T11:54:06.848006498+08:00 stderr F     return ctx.invoke(self.callback, **ctx.params)
2024-10-10T11:54:06.8480104+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
2024-10-10T11:54:06.848574054+08:00 stderr F     return __callback(*args, **kwargs)
2024-10-10T11:54:06.848581945+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py", line 514, in main
2024-10-10T11:54:06.848585131+08:00 stderr F     sf_node_eval_param = preprocess_sf_node_eval_param(
2024-10-10T11:54:06.848588019+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py", line 271, in preprocess_sf_node_eval_param
2024-10-10T11:54:06.848590679+08:00 stderr F     comp_def = get_comp_def(param.domain, param.name, param.version)
2024-10-10T11:54:06.848593544+08:00 stderr F   File "/usr/local/lib/python3.10/site-packages/secretflow/component/entry.py", line 156, in get_comp_def
2024-10-10T11:54:06.848596431+08:00 stderr F     key in COMP_MAP
2024-10-10T11:54:06.848602152+08:00 stderr F AssertionError: key data_prep/psi:0.0.7 is not in component list ['data_prep/union:0.0.1', 'data_prep/train_test_split:0.0.1', 'data_prep/psi:0.0.5', 'data_filter/sample:0.0.1', 'ml.train/ss_sgd_train:0.0.1', 'ml.predict/ss_sgd_predict:0.0.2', 'data_filter/feature_filter:0.0.1', 'preprocessing/binary_op:0.0.2', 'feature/vert_binning:0.0.2', 'feature/vert_woe_binning:0.0.2', 'preprocessing/vert_bin_substitution:0.0.1', 'data_filter/condition_filter:0.0.1', 'stats/ss_vif:0.0.1', 'stats/ss_pearsonr:0.0.1', 'ml.eval/ss_pvalue:0.0.1', 'stats/table_statistics:0.0.2', 'stats/groupby_statistics:0.0.3', 'stats/stats_psi:0.0.1', 'ml.eval/biclassification_eval:0.0.1', 'ml.eval/regression_eval:0.0.1', 'ml.eval/prediction_bias_eval:0.0.1', 'ml.predict/sgb_predict:0.0.3', 'ml.train/sgb_train:0.0.3', 'ml.predict/ss_xgb_predict:0.0.2', 'ml.train/ss_xgb_train:0.0.1', 'ml.predict/ss_glm_predict:0.0.2', 'ml.train/ss_glm_train:0.0.3', 'ml.train/slnn_train:0.0.1', 'ml.predict/slnn_predict:0.0.2', 'preprocessing/onehot_encode:0.0.3', 'preprocessing/substitution:0.0.2', 'preprocessing/case_when:0.0.1', 'preprocessing/fillna:0.0.1', 'io/read_data:0.0.1', 'io/write_data:0.0.1', 'preprocessing/feature_calculate:0.0.1', 'io/identity:0.0.1', 'model/model_export:0.0.1', 'preprocessing/cast:0.0.1', 'postprocessing/score_card_transformer:0.0.1']
```

**Comment by 123zzc** [comment]
在镜像中加入secretflow后不报错了。但是job卡住：
<img width="173" alt="1728549084746" src="https://github.com/user-attachments/assets/b72aa6c7-0a58-485e-ac2b-30f5b4d5f4ea">
在kusica中查询任务状态：
<img width="1164" alt="1728549112756" src="https://github.com/user-attachments/assets/8cd07ce0-936f-4cfa-bc9d-446a94de3d63">

**Comment by 123zzc** [comment]
key data_prep/psi:0.0.7 is not in component list  是不是缺少组件？

**Comment by BrainWH** [comment]
Log output中的报错日志是由于psi的版本不一致，可以执行secretflow component ls 查询psi的日志信息

**Comment by BrainWH** [comment]
检查一下pad\kuscia\secretflow的版本信息，确认是否是对应版本

**Comment by 123zzc** [comment]
> 检查一下pad\kuscia\secretflow的版本信息，确认是否是对应版本

没有单独使用docker启动secretflow，但kuscia启动时指定的secretflow版本为：
export SECRETFLOW_IMAGE=secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-anolis8:1.7.0b0

**Comment by 123zzc** [comment]
> > 检查一下pad\kuscia\secretflow的版本信息，确认是否是对应版本
> 
> 没有单独使用docker启动secretflow，但kuscia启动时指定的secretflow版本为： export SECRETFLOW_IMAGE=secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-anolis8:1.7.0b0
<img width="1165" alt="1728612396446" src="https://github.com/user-attachments/assets/8b1cae88-e7b1-45b0-afe3-5ffd544b35df">

**Comment by BrainWH** [comment]
你好，这是正确的版本对应信息：https://github.com/secretflow/secretpad?tab=readme-ov-file#versions

**Comment by 123zzc** [comment]
> 你好，这是正确的版本对应信息：https://github.com/secretflow/secretpad?tab=readme-ov-file#versions

更新版本后报错信息改变：
![image](https://github.com/user-attachments/assets/970b1922-4c80-4ea2-b013-22f724a91a78)

**Comment by BrainWH** [comment]
看目前的报错信息是csv文件不存在，检查一下该文件

**Comment by 123zzc** [comment]
> 看目前的报错信息是csv文件不存在，检查一下该文件

确实在目录下不存在该文件，但这个文件应该是求交是产生的临时文件。现在情况是我本地启动secretpad，链接远程kuscia。数据集文件是存在本地文件目录下，请问是否会有影响。

**Comment by BrainWH** [comment]
会有影响的，因为secretpad和kuscia没有做数据挂载。针对这种场景，需要使用oss数据源

**Comment by 123zzc** [comment]
> 会有影响的，因为secretpad和kuscia没有做数据挂载。针对这种场景，需要使用oss数据源
部署oss问题解决。谢谢！
