### ISSUE TITLE
数据集上二分类模型的统计评估

### ISSUE THREAD

**Issue by T-ze-yu** [secretflow/secretpad#27]
![1e101dd62cfdc5cff1ff8e84d2c4b4a](https://github.com/secretflow/secretpad/assets/75960285/aafe67ff-cd30-4e9d-856c-8ac84a5080e8)
使用kuscia  API调用实现该功能的计算，可以给一个具体的task_input_config的参数配置示例吗

**Comment by CodePorterL** [comment]
halo  
attr_paths中有两个值 第一个值对应的是标签列 第二个值对应的是预测列
"attr_paths": ["input/in_ds/label", "input/in_ds/prediction"],
attrs是一个list，list的参数对应是的attr_paths里的值
"attrs": [{
            "is_na": false,
            "ss": ["y"]
          }, {
            "is_na": false,
            "ss": ["pred"]
          }]

上列示例中：
"input/in_ds/label" 对应的是
         {
            "is_na": false,
            "ss": ["y"]
          }，
"input/in_ds/prediction"对应的是
       {
            "is_na": false,
            "ss": ["pred"]
          }
![image](https://github.com/secretflow/secretpad/assets/91072507/eb9a9380-e462-4c17-a542-fe9a69ca3abf)

**Comment by T-ze-yu** [comment]
![image](https://github.com/secretflow/secretpad/assets/75960285/c393d95f-b028-4b0b-822a-000d38d82beb)
完整的是这样吗？我还是报错，下面是日志：
![image](https://github.com/secretflow/secretpad/assets/75960285/29284b5b-5048-4739-8b92-714aeffa9e76)

**Comment by T-ze-yu** [comment]
![image](https://github.com/secretflow/secretpad/assets/75960285/4d592cd2-1414-4e67-8d2d-52a8449eeacd)

**Comment by CodePorterL** [comment]
你好 这边提供一个taskinputconfig 麻烦看一下
      {
        "sf_datasource_config": {
          "lizi-test": {
            "id": "default-data-source"
          },
          "ant-alice": {
            "id": "default-data-source"
          }
        },
        "sf_cluster_desc": {
          "parties": ["lizi-test", "ant-alice"],
          "devices": [{
            "name": "spu",
            "type": "spu",
            "parties": ["lizi-test", "ant-alice"],
            "config": "{\"runtime_config\":{\"protocol\":\"REF2K\",\"field\":\"FM64\"},\"link_desc\":{\"connect_retry_times\":60,\"connect_retry_interval_ms\":1000,\"brpc_channel_protocol\":\"http\",\"brpc_channel_connection_type\":\"pooled\",\"recv_timeout_ms\":1200000,\"http_timeout_ms\":1200000}}"
          }, {
            "name": "heu",
            "type": "heu",
            "parties": ["lizi-test", "ant-alice"],
            "config": "{\"mode\": \"PHEU\", \"schema\": \"paillier\", \"key_size\": 2048}"
          }],
          "ray_fed_config": {
            "cross_silo_comm_backend": "brpc_link"
          }
        },
        "sf_node_eval_param": {
          "domain": "ml.eval",
          "name": "biclassification_eval",
          "version": "0.0.1",
          "attr_paths": ["input/in_ds/label", "input/in_ds/prediction"],
          "attrs": [{
            "is_na": false,
            "ss": ["y"]
          }, {
            "is_na": false,
            "ss": ["pred"]
          }]
        },
        "sf_output_uris": ["ftks-zrzwsigy-node-14-output-0"],
        "sf_input_ids": ["ftks-zrzwsigy-node-13-output-0"],
        "sf_output_ids": ["ftks-zrzwsigy-node-14-output-0"]
      }

**Comment by T-ze-yu** [comment]
也就是说没有bucket_size、min_item_cnt_per_bucket这两个参数，但我运行后还是报一样的错误，可以确定一下sf_input_ids是预测得到的结果表的ID吗？下面是我完整的taskinputconfig：
{
    "sf_datasource_config": {
        "p119": {
            "id": "default-data-source"
        },
        "p131": {
            "id": "default-data-source"
        }
    },
    "sf_cluster_desc": {
        "parties": [
            "p119",
            "p131"
        ],
        "devices": [
            {
                "name": "spu",
                "type": "spu",
                "parties": [
                    "p119",
                    "p131"
                ],
                "config": "{\"runtime_config\":{\"protocol\":\"REF2K\",\"field\":\"FM64\"},\"link_desc\":{\"connect_retry_times\":60,\"connect_retry_interval_ms\":1000,\"brpc_channel_protocol\":\"http\",\"brpc_channel_connection_type\":\"pooled\",\"recv_timeout_ms\":1200000,\"http_timeout_ms\":1200000}}"
            },
            {
                "name": "heu",
                "type": "heu",
                "parties": [
                    "p119",
                    "p131"
                ],
                "config": "{\"mode\": \"PHEU\", \"schema\": \"paillier\", \"key_size\": 2048}"
            }
        ],
        "ray_fed_config": {
            "cross_silo_comm_backend": "brpc_link"
        }
    },
    "sf_node_eval_param": {
        "domain": "ml.eval",
        "name": "biclassification_eval",
        "version": "0.0.1",
        "attr_paths": [
            "input/in_ds/label",
            "input/in_ds/prediction"
        ],
        "attrs": [
        {
                "is_na": false,
                "ss": [
                    "y"
                ]
        }, 
        {
                "is_na": false,
                "ss": [
                    "pred"
                ]
        }
        ]
    },
    "sf_output_uris": [
        "eval-sgd"
    ],
    "sf_output_ids": [
        "eval-sgd"
    ],
    "sf_input_ids": [
        "pred-sgd"
    ]
}

**Comment by CodePorterL** [comment]
这个是p2p模式还是中心化模式部署呢 我这边看了一下 两种模式传参不太一样

**Comment by T-ze-yu** [comment]
p2p的

**Comment by CodePorterL** [comment]
sorry  之前查看的时候正在切换镜像 导致数据不全 是有bucket_size、min_item_cnt_per_bucket这两个参数的
{
        "sf_datasource_config": {
          "bob": {
            "id": "default-data-source"
          },
          "alice": {
            "id": "default-data-source"
          }
        },
        "sf_cluster_desc": {
          "parties": ["bob", "alice"],
          "devices": [{
            "name": "spu",
            "type": "spu",
            "parties": ["bob", "alice"],
            "config": "{\"runtime_config\":{\"protocol\":\"SEMI2K\",\"field\":\"FM128\"},\"link_desc\":{\"connect_retry_times\":60,\"connect_retry_interval_ms\":1000,\"brpc_channel_protocol\":\"http\",\"brpc_channel_connection_type\":\"pooled\",\"recv_timeout_ms\":1200000,\"http_timeout_ms\":1200000}}"
          }, {
            "name": "heu",
            "type": "heu",
            "parties": ["bob", "alice"],
            "config": "{\"mode\": \"PHEU\", \"schema\": \"paillier\", \"key_size\": 2048}"
          }],
          "ray_fed_config": {
            "cross_silo_comm_backend": "brpc_link"
          }
        },
        "sf_node_eval_param": {
          "domain": "ml.eval",
          "name": "biclassification_eval",
          "version": "0.0.1",
          "attr_paths": ["input/in_ds/label", "input/in_ds/prediction", "bucket_size", "min_item_cnt_per_bucket"],
          "attrs": [{
            "is_na": false,
            "ss": ["y"]
          }, {
            "is_na": false,
            "ss": ["pred"]
          }, {
            "i64": 10.0,
            "is_na": false
          }, {
            "i64": 5.0,
            "is_na": false
          }]
        },
        "sf_output_uris": ["rkkl-xvtahmxk-node-14-output-0"],
        "sf_input_ids": ["qauc-xvtahmxk-node-13-output-0"],
        "sf_output_ids": ["rkkl-xvtahmxk-node-14-output-0"]
      }

**Comment by T-ze-yu** [comment]
还是一样的报错，最开始用的就是这个格式

**Comment by CodePorterL** [comment]
halo 麻烦提供一下引擎镜像的版本，可能参数存在问题

**Comment by T-ze-yu** [comment]
Kuscla verslon afbd526
secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia   latest

**Comment by yushiqie** [comment]
输入表的 pred-sgd 是怎么产出的啊，可以看下 domaindata 的详情吗

**Comment by T-ze-yu** [comment]
{
    "status": {
        "code": 0,
        "message": "success",
        "details": []
    },
    "data": {
        "domaindata_id": "pred-sgd",
        "name": "pred",
        "type": "table",
        "relative_uri": "pred-sgd.csv",
        "domain_id": "p119",
        "datasource_id": "default-data-source",
        "attributes": {
            "dist_data": "{\n  \"name\": \"pred\",\n  \"type\": \"sf.table.individual\",\n  \"meta\": {\n    \"@type\": \"type.googleapis.com/secretflow.spec.v1.IndividualTable\",\n    \"schema\": {\n      \"ids\": [\n        \"id2\"\n      ],\n      \"labels\": [\n        \"y\",\n        \"pred\"\n      ],\n      \"idTypes\": [\n        \"int\"\n      ],\n      \"labelTypes\": [\n        \"int\",\n        \"float\"\n      ],\n      \"features\": [],\n      \"featureTypes\": []\n    },\n    \"lineCount\": \"2473\"\n  },\n  \"dataRefs\": [\n    {\n      \"uri\": \"pred-sgd.csv\",\n      \"party\": \"p119\",\n      \"format\": \"csv\"\n    }\n  ]\n}"
        },
        "partition": null,
        "columns": [
            {
                "name": "id2",
                "type": "int",
                "comment": "id",
                "not_nullable": false
            },
            {
                "name": "y",
                "type": "int",
                "comment": "label",
                "not_nullable": false
            },
            {
                "name": "pred",
                "type": "float",
                "comment": "label",
                "not_nullable": false
            }
        ],
        "vendor": "secretflow",
        "status": "Available",
        "author": "p119",
        "file_format": "UNKNOWN"
    }
}

**Comment by T-ze-yu** [comment]
使用逻辑回归模型预测生成的pred-sgd，下面是预测时的taskinputconfig
{
    "sf_datasource_config": {
        "p119": {
            "id": "default-data-source"
        },
        "p131": {
            "id": "default-data-source"
        }
    },
    "sf_cluster_desc": {
        "parties": [
            "p119",
            "p131"
        ],
        "devices": [
            {
                "name": "spu",
                "type": "spu",
                "parties": [
                    "p119",
                    "p131"
                ],
                "config": "{\"runtime_config\":{\"protocol\":\"REF2K\",\"field\":\"FM64\"},\"link_desc\":{\"connect_retry_times\":60,\"connect_retry_interval_ms\":1000,\"brpc_channel_protocol\":\"http\",\"brpc_channel_connection_type\":\"pooled\",\"recv_timeout_ms\":1200000,\"http_timeout_ms\":1200000}}"
            },
            {
                "name": "heu",
                "type": "heu",
                "parties": [
                    "p119",
                    "p131"
                ],
                "config": "{\"mode\": \"PHEU\", \"schema\": \"paillier\", \"key_size\": 2048}"
            }
        ],
        "ray_fed_config": {
            "cross_silo_comm_backend": "brpc_link"
        }
    },
    "sf_node_eval_param": {
        "domain": "ml.predict",
        "name": "ss_sgd_predict",
        "version": "0.0.1",
        "attr_paths": [
            "batch_size",
            "receiver",
            "pred_name",
            "save_ids",
            "save_label"
        ],
        "attrs": [
            {
                "i64": 64,
                "is_na": false
            },
            {
                "is_na": false,
                "s": "p119"
            },
            {
                "is_na": false,
                "s": "pred"
            },
            {
                "b": true,
                "is_na": false
            },
            {
                "b": true,
                "is_na": false
            }
        ]
    },
    "sf_output_uris": [
        "pred-sgd.csv"
    ],
    "sf_output_ids": [
        "pred-sgd"
    ],
    "sf_input_ids": [
        "output-model",
        "test-dataset"
    ]
}

**Comment by CodePorterL** [comment]
"sf_input_ids"里的值只能填一个

**Comment by T-ze-yu** [comment]
"sf_input_ids": ["qauc-xvtahmxk-node-13-output-0"]
你们给的这个输入是什么，不是预测输出的结果表吗

**Comment by T-ze-yu** [comment]
![image](https://github.com/secretflow/secretpad/assets/75960285/5eeee84e-36b7-438a-8a7c-b28ee3fc7405)
输入应该有两个，但给的示例只有一个，代码报错也是这个原因：
![image](https://github.com/secretflow/secretpad/assets/75960285/47b06c56-7ae7-4b71-9315-b1f846c6cd90)
将两边的结果打印如下：
![image](https://github.com/secretflow/secretpad/assets/75960285/bfb75343-1d67-4979-9d3f-b69e3d6c66f6)
需要两个，而我们只输入了一个

**Comment by haha-zwx-ooo** [comment]
> ![image](https://private-user-images.githubusercontent.com/75960285/300369429-5eeee84e-36b7-438a-8a7c-b28ee3fc7405.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTkxNTgsIm5iZiI6MTcwNjUxODg1OCwicGF0aCI6Ii83NTk2MDI4NS8zMDAzNjk0MjktNWVlZWU4NGUtMzZiNy00MzhhLThhN2MtYjI4ZWUzZmM3NDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA5MDA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMmRhNDFkZTYwOGYwYmJmZDI4YmY2NzJlNGE1MmMxM2NiMTkwZmM5NzIyYWVkZWE5MWVhNTYwYWVjZTY4NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.guMyeFa-xXXxeYI6S5Lu807sXzWnvmC_PlVCa6S2jvI) 输入应该有两个，但给的示例只有一个，代码报错也是这个原因： ![image](https://private-user-images.githubusercontent.com/75960285/300369878-47b06c56-7ae7-4b71-9315-b1f846c6cd90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTkxNTgsIm5iZiI6MTcwNjUxODg1OCwicGF0aCI6Ii83NTk2MDI4NS8zMDAzNjk4NzgtNDdiMDZjNTYtN2FlNy00YjcxLTkzMTUtYjFmODQ2YzZjZDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA5MDA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ZTc4YTA3NTVjNDFmNjQ5MGQwNjA2NTZmYjNhMDA5ZGEzZGYyZTQxMDNmZDZjZmUyZDUwMDBiYjYyMDBlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7cbceJnEJUsy3rw_k93rwKMWgXZ1IFdNh6dEtWeopjE) 将两边的结果打印如下： ![image](https://private-user-images.githubusercontent.com/75960285/300370029-bfb75343-1d67-4979-9d3f-b69e3d6c66f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTkxNTgsIm5iZiI6MTcwNjUxODg1OCwicGF0aCI6Ii83NTk2MDI4NS8zMDAzNzAwMjktYmZiNzUzNDMtMWQ2Ny00OTc5LTlkM2YtYjY5ZTNkNmM2NmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA5MDA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYjUwMjFlZDA0YzA2NTg4Zjc5N2Y0OWI5ZmUyMTA4ZWRjMzlkYzYwYmU2ZDkzYTk5MDVlMzM4ZDgwNWU5ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P8ikls0NWXo7pidUiDwJT6R67TBXbT0rfIVozj3tgbM) 需要两个，而我们只输入了一个


能提供下完整的引擎日志吗？

**Comment by T-ze-yu** [comment]
好的
2024-01-29T14:31:23.323506663+08:00 stderr F WARNING:root:Since the GPL-licensed package `unidecode` is not installed, using Python's `unicodedata` package which yields worse results.
2024-01-29T14:31:23.698848533+08:00 stdout F 2024-01-29 06:31:23,698|p119|INFO|secretflow|entry.py:start_ray:55| ray_conf: RayConfig(ray_node_ip_address='lr-eval10-0-global.p119.svc', ray_node_manager_port=0, ray_object_manager_port=0, ray_client_server_port=0, ray_worker_ports=[], ray_gcs_port=8081)
2024-01-29T14:31:23.698870581+08:00 stdout F 2024-01-29 06:31:23,698|p119|INFO|secretflow|entry.py:start_ray:59| Trying to start ray head node at lr-eval10-0-global.p119.svc, start command: RAY_BACKEND_LOG_LEVEL=debug RAY_grpc_enable_http_proxy=true OMP_NUM_THREADS=4 ray start --head --include-dashboard=false --disable-usage-stats --num-cpus=32 --node-ip-address=lr-eval10-0-global.p119.svc --port=8081
2024-01-29T14:31:27.956200997+08:00 stdout F 2024-01-29 06:31:27,955|p119|INFO|secretflow|entry.py:start_ray:76| 2024-01-29 06:31:24,473	INFO usage_lib.py:490 -- Usage stats collection is disabled.
2024-01-29T14:31:27.956238668+08:00 stdout F 2024-01-29 06:31:24,474	INFO scripts.py:702 -- Local node IP: lr-eval10-0-global.p119.svc
2024-01-29T14:31:27.956243317+08:00 stdout F 2024-01-29 06:31:27,825	SUCC scripts.py:739 -- --------------------
2024-01-29T14:31:27.956246684+08:00 stdout F 2024-01-29 06:31:27,826	SUCC scripts.py:740 -- Ray runtime started.
2024-01-29T14:31:27.956249164+08:00 stdout F 2024-01-29 06:31:27,826	SUCC scripts.py:741 -- --------------------
2024-01-29T14:31:27.956252334+08:00 stdout F 2024-01-29 06:31:27,826	INFO scripts.py:743 -- Next steps
2024-01-29T14:31:27.956257065+08:00 stdout F 2024-01-29 06:31:27,826	INFO scripts.py:744 -- To connect to this Ray runtime from another node, run
2024-01-29T14:31:27.956259768+08:00 stdout F 2024-01-29 06:31:27,826	INFO scripts.py:747 --   ray start --address='lr-eval10-0-global.p119.svc:8081'
2024-01-29T14:31:27.956262379+08:00 stdout F 2024-01-29 06:31:27,826	INFO scripts.py:763 -- Alternatively, use the following Python code:
2024-01-29T14:31:27.956264875+08:00 stdout F 2024-01-29 06:31:27,826	INFO scripts.py:765 -- import ray
2024-01-29T14:31:27.956269066+08:00 stdout F 2024-01-29 06:31:27,826	INFO scripts.py:769 -- ray.init(address='auto', _node_ip_address='lr-eval10-0-global.p119.svc')
2024-01-29T14:31:27.956271579+08:00 stdout F 2024-01-29 06:31:27,826	INFO scripts.py:781 -- To connect to this Ray runtime from outside of the cluster, for example to
2024-01-29T14:31:27.956274333+08:00 stdout F 2024-01-29 06:31:27,826	INFO scripts.py:785 -- connect to a remote cluster from your laptop directly, use the following
2024-01-29T14:31:27.956276736+08:00 stdout F 2024-01-29 06:31:27,826	INFO scripts.py:789 -- Python code:
2024-01-29T14:31:27.956279184+08:00 stdout F 2024-01-29 06:31:27,827	INFO scripts.py:791 -- import ray
2024-01-29T14:31:27.956281559+08:00 stdout F 2024-01-29 06:31:27,827	INFO scripts.py:792 -- ray.init(address='ray://<head_node_ip_address>:10001')
2024-01-29T14:31:27.956284019+08:00 stdout F 2024-01-29 06:31:27,827	INFO scripts.py:801 -- To see the status of the cluster, use
2024-01-29T14:31:27.956286423+08:00 stdout F 2024-01-29 06:31:27,827	INFO scripts.py:802 --   ray status
2024-01-29T14:31:27.956288847+08:00 stdout F 2024-01-29 06:31:27,827	INFO scripts.py:812 -- If connection fails, check your firewall settings and network configuration.
2024-01-29T14:31:27.95629126+08:00 stdout F 2024-01-29 06:31:27,827	INFO scripts.py:820 -- To terminate the Ray runtime, run
2024-01-29T14:31:27.956293748+08:00 stdout F 2024-01-29 06:31:27,827	INFO scripts.py:821 --   ray stop
2024-01-29T14:31:27.956296043+08:00 stdout F 
2024-01-29T14:31:27.95629892+08:00 stdout F 2024-01-29 06:31:27,955|p119|INFO|secretflow|entry.py:start_ray:77| Succeeded to start ray head node at lr-eval10-0-global.p119.svc.
2024-01-29T14:31:27.960141384+08:00 stderr F Traceback (most recent call last):
2024-01-29T14:31:27.960160774+08:00 stderr F   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2024-01-29T14:31:27.960177937+08:00 stderr F     return _run_code(code, main_globals, None,
2024-01-29T14:31:27.960181499+08:00 stderr F   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
2024-01-29T14:31:27.960184334+08:00 stderr F     exec(code, run_globals)
2024-01-29T14:31:27.960187603+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/secretflow/kuscia/entry.py", line 294, in <module>
2024-01-29T14:31:27.960190178+08:00 stderr F     main()
2024-01-29T14:31:27.960192811+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
2024-01-29T14:31:27.960195263+08:00 stderr F     return self.main(*args, **kwargs)
2024-01-29T14:31:27.960197655+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
2024-01-29T14:31:27.960200018+08:00 stderr F     rv = self.invoke(ctx)
2024-01-29T14:31:27.960202501+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
2024-01-29T14:31:27.960205166+08:00 stderr F     return ctx.invoke(self.callback, **ctx.params)
2024-01-29T14:31:27.960207618+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
2024-01-29T14:31:27.960210277+08:00 stderr F     return __callback(*args, **kwargs)
2024-01-29T14:31:27.960212761+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/secretflow/kuscia/entry.py", line 261, in main
2024-01-29T14:31:27.960215181+08:00 stderr F     sf_node_eval_param = preprocess_sf_node_eval_param(
2024-01-29T14:31:27.960219669+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/secretflow/kuscia/entry.py", line 94, in preprocess_sf_node_eval_param
2024-01-29T14:31:27.960222126+08:00 stderr F     assert len(comp_def.inputs) == len(
2024-01-29T14:31:27.960224611+08:00 stderr F AssertionError: cnt of sf_input_ids doesn't match cnt of comp_def.inputs.

**Comment by haha-zwx-ooo** [comment]
> 好的 2024-01-29T14:31:23.323506663+08:00 stderr F WARNING:root:Since the GPL-licensed package `unidecode` is not installed, using Python's `unicodedata` package which yields worse results. 2024-01-29T14:31:23.698848533+08:00 stdout F 2024-01-29 06:31:23,698|p119|INFO|secretflow|entry.py:start_ray:55| ray_conf: RayConfig(ray_node_ip_address='lr-eval10-0-global.p119.svc', ray_node_manager_port=0, ray_object_manager_port=0, ray_client_server_port=0, ray_worker_ports=[], ray_gcs_port=8081) 2024-01-29T14:31:23.698870581+08:00 stdout F 2024-01-29 06:31:23,698|p119|INFO|secretflow|entry.py:start_ray:59| Trying to start ray head node at lr-eval10-0-global.p119.svc, start command: RAY_BACKEND_LOG_LEVEL=debug RAY_grpc_enable_http_proxy=true OMP_NUM_THREADS=4 ray start --head --include-dashboard=false --disable-usage-stats --num-cpus=32 --node-ip-address=lr-eval10-0-global.p119.svc --port=8081 2024-01-29T14:31:27.956200997+08:00 stdout F 2024-01-29 06:31:27,955|p119|INFO|secretflow|entry.py:start_ray:76| 2024-01-29 06:31:24,473 INFO usage_lib.py:490 -- Usage stats collection is disabled. 2024-01-29T14:31:27.956238668+08:00 stdout F 2024-01-29 06:31:24,474 INFO scripts.py:702 -- Local node IP: lr-eval10-0-global.p119.svc 2024-01-29T14:31:27.956243317+08:00 stdout F 2024-01-29 06:31:27,825 SUCC scripts.py:739 -- -------------------- 2024-01-29T14:31:27.956246684+08:00 stdout F 2024-01-29 06:31:27,826 SUCC scripts.py:740 -- Ray runtime started. 2024-01-29T14:31:27.956249164+08:00 stdout F 2024-01-29 06:31:27,826 SUCC scripts.py:741 -- -------------------- 2024-01-29T14:31:27.956252334+08:00 stdout F 2024-01-29 06:31:27,826 INFO scripts.py:743 -- Next steps 2024-01-29T14:31:27.956257065+08:00 stdout F 2024-01-29 06:31:27,826 INFO scripts.py:744 -- To connect to this Ray runtime from another node, run 2024-01-29T14:31:27.956259768+08:00 stdout F 2024-01-29 06:31:27,826 INFO scripts.py:747 -- ray start --address='lr-eval10-0-global.p119.svc:8081' 2024-01-29T14:31:27.956262379+08:00 stdout F 2024-01-29 06:31:27,826 INFO scripts.py:763 -- Alternatively, use the following Python code: 2024-01-29T14:31:27.956264875+08:00 stdout F 2024-01-29 06:31:27,826 INFO scripts.py:765 -- import ray 2024-01-29T14:31:27.956269066+08:00 stdout F 2024-01-29 06:31:27,826 INFO scripts.py:769 -- ray.init(address='auto', _node_ip_address='lr-eval10-0-global.p119.svc') 2024-01-29T14:31:27.956271579+08:00 stdout F 2024-01-29 06:31:27,826 INFO scripts.py:781 -- To connect to this Ray runtime from outside of the cluster, for example to 2024-01-29T14:31:27.956274333+08:00 stdout F 2024-01-29 06:31:27,826 INFO scripts.py:785 -- connect to a remote cluster from your laptop directly, use the following 2024-01-29T14:31:27.956276736+08:00 stdout F 2024-01-29 06:31:27,826 INFO scripts.py:789 -- Python code: 2024-01-29T14:31:27.956279184+08:00 stdout F 2024-01-29 06:31:27,827 INFO scripts.py:791 -- import ray 2024-01-29T14:31:27.956281559+08:00 stdout F 2024-01-29 06:31:27,827 INFO scripts.py:792 -- ray.init(address='ray://<head_node_ip_address>:10001') 2024-01-29T14:31:27.956284019+08:00 stdout F 2024-01-29 06:31:27,827 INFO scripts.py:801 -- To see the status of the cluster, use 2024-01-29T14:31:27.956286423+08:00 stdout F 2024-01-29 06:31:27,827 INFO scripts.py:802 -- ray status 2024-01-29T14:31:27.956288847+08:00 stdout F 2024-01-29 06:31:27,827 INFO scripts.py:812 -- If connection fails, check your firewall settings and network configuration. 2024-01-29T14:31:27.95629126+08:00 stdout F 2024-01-29 06:31:27,827 INFO scripts.py:820 -- To terminate the Ray runtime, run 2024-01-29T14:31:27.956293748+08:00 stdout F 2024-01-29 06:31:27,827 INFO scripts.py:821 -- ray stop 2024-01-29T14:31:27.956296043+08:00 stdout F 2024-01-29T14:31:27.95629892+08:00 stdout F 2024-01-29 06:31:27,955|p119|INFO|secretflow|entry.py:start_ray:77| Succeeded to start ray head node at lr-eval10-0-global.p119.svc. 2024-01-29T14:31:27.960141384+08:00 stderr F Traceback (most recent call last): 2024-01-29T14:31:27.960160774+08:00 stderr F File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main 2024-01-29T14:31:27.960177937+08:00 stderr F return _run_code(code, main_globals, None, 2024-01-29T14:31:27.960181499+08:00 stderr F File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code 2024-01-29T14:31:27.960184334+08:00 stderr F exec(code, run_globals) 2024-01-29T14:31:27.960187603+08:00 stderr F File "/usr/local/lib/python3.8/site-packages/secretflow/kuscia/entry.py", line 294, in 2024-01-29T14:31:27.960190178+08:00 stderr F main() 2024-01-29T14:31:27.960192811+08:00 stderr F File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in **call** 2024-01-29T14:31:27.960195263+08:00 stderr F return self.main(*args, **kwargs) 2024-01-29T14:31:27.960197655+08:00 stderr F File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main 2024-01-29T14:31:27.960200018+08:00 stderr F rv = self.invoke(ctx) 2024-01-29T14:31:27.960202501+08:00 stderr F File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke 2024-01-29T14:31:27.960205166+08:00 stderr F return ctx.invoke(self.callback, **ctx.params) 2024-01-29T14:31:27.960207618+08:00 stderr F File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke 2024-01-29T14:31:27.960210277+08:00 stderr F return __callback(*args, **kwargs) 2024-01-29T14:31:27.960212761+08:00 stderr F File "/usr/local/lib/python3.8/site-packages/secretflow/kuscia/entry.py", line 261, in main 2024-01-29T14:31:27.960215181+08:00 stderr F sf_node_eval_param = preprocess_sf_node_eval_param( 2024-01-29T14:31:27.960219669+08:00 stderr F File "/usr/local/lib/python3.8/site-packages/secretflow/kuscia/entry.py", line 94, in preprocess_sf_node_eval_param 2024-01-29T14:31:27.960222126+08:00 stderr F assert len(comp_def.inputs) == len( 2024-01-29T14:31:27.960224611+08:00 stderr F AssertionError: cnt of sf_input_ids doesn't match cnt of comp_def.inputs.



逻辑回归+二分类吗？ ss_sgd_predict 的输出有吗？ 或者你进入 任务发起方的kuscia docker 容器中执行 kubectl get kt

**Comment by T-ze-yu** [comment]
是的，输出就是pred-sgd，之前的记录有信息的ss_sgd_predict 参数，以及具体pred-sgd的数据详情

**Comment by T-ze-yu** [comment]
预测时的taskinputconfig：https://github.com/secretflow/secretpad/issues/27#issuecomment-1911763472
 domaindata 的详情：https://github.com/secretflow/secretpad/issues/27#issuecomment-1911759274

**Comment by haha-zwx-ooo** [comment]
> 预测时的taskinputconfig：[#27 (comment)](https://github.com/secretflow/secretpad/issues/27#issuecomment-1911763472) domaindata 的详情：[#27 (comment)](https://github.com/secretflow/secretpad/issues/27#issuecomment-1911759274)

从你发的参数看是没有问题的
发起者是 p119 ？ p2p 模式？ 
docker exec -it {USER}-kuscia-autonomy-p119  
kubectl get kt 
结果截个图看下呢

**Comment by T-ze-yu** [comment]
![Uploading 图片1.png…]()

**Comment by T-ze-yu** [comment]
![Uploading 图片1.png…]()

**Comment by T-ze-yu** [comment]
可以看得到图片吗？我好像上传不了了

**Comment by T-ze-yu** [comment]
![Uploading image.png…]()

**Comment by T-ze-yu** [comment]
secretflow-image版本为1.3.0.dev20231120，该版本在运行这个组件时参数上传有bug，需要将secretflow-image版本升级
