### ISSUE TITLE
二次开发问题

### ISSUE THREAD

**Issue by zunpan** [secretflow/secretpad#34]
我按照SecretPad的p2p部署教程[https://www.secretflow.org.cn/docs/quickstart/dbd670doqfio1puq]部署并跑通了。
![image](https://github.com/secretflow/secretpad/assets/45265770/7f90ef3d-b013-41ec-99fb-79cac015636f)

现在我想二次开发SecretPad后端，我的理解是我不需要再部署kuscia，用已经有的root-kuscia-autonomy服务就行，所以我把已经跑起来的SecretPad的参数以配置参数形式启动后端，但是没有成功，请问该怎么才能把后端启起来
![image](https://github.com/secretflow/secretpad/assets/45265770/e4774a0b-b2b3-4633-9726-de73dedce058)
![image](https://github.com/secretflow/secretpad/assets/45265770/7c6879df-9e94-4d0f-abe2-1b4708c502f0)

**Comment by zunpan** [comment]
我现在把kuscia/p2p/node1-certs的证书复制到了secretpad/config/certs里面，现在启动报错

io.grpc.StatusRuntimeException: UNAVAILABLE: Failed ALPN negotiation: Unable to find compatible protocol
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
        at io.grpc.Status.asRuntimeException(Status.java:539)
        at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:662)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
        at org.secretflow.secretpad.manager.integration.job.JobManager.startSync(JobManager.java:131)
        at org.secretflow.secretpad.service.listener.JobSyncListener.onApplicationEvent(JobSyncListener.java:51)
        at org.secretflow.secretpad.service.listener.JobSyncListener.onApplicationEvent(JobSyncListener.java:35)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:174)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:445)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
        at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:109)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:80)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:80)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.secretflow.secretpad.web.SecretPadApplication.main(SecretPadApplication.java:59)

请问该怎么解决

**Comment by zimu-yuxi** [comment]
请问下我们是想要本地调试吗？可以尝试以下操作
1.停掉P2P包部署的pad容器
2.把kuscia/p2p/node1-certs的证书复制到了secretpad/config/certs里面
3.项目config目录统计新建db文件夹，新增secretpad.splite文件，也可以将P2P包部署的pad中的secretpad.split复制出来
4.配置jvm启动参数-Dspring.profiles.active=dev 
5.再尝试运行下项目
如实在不行您可添加技术支持（secretflow02）寻求帮助
