### ISSUE TITLE
本地运行secretpad报错，无法正常连接数据库相关服务

### ISSUE THREAD

**Issue by Rcvisual** [secretflow/secretpad#59]
dockers中查询到的
- OS: Windows
- Docker: Docker version 25.0.3
-  secretpad 0.6.0b, kuscia 0.7.0b, secretflow 1.5.0b
- Mode center
- Build mpc

本地起来secretpad的输出
secretpad  version: 0.5.0b0
kuscia     version: 0.6.0b0
secretflow version: 1.4.0b0

**Additional context**
报错：
2024-04-25T09:44:21.021+08:00 ERROR 13532 --- [ault-executor-2] o.s.s.m.integration.job.JobManager       : watchJob onError: UNAVAILABLE: Network closed for unknown reason

io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.Status.asRuntimeException(Status.java:539)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:576)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:757)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:736)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)

是不是版本不一样的问题

**Comment by angang007** [comment]
请问您解决了么  谢谢
