### ISSUE TITLE
secetpad本地启动报错

### ISSUE THREAD

**Issue by wangzeyu135798** [secretflow/secretpad#64]
![image](https://github.com/secretflow/secretpad/assets/39690172/1797c589-338f-49f8-9426-32522186d41e)
你好，进入到secretflow-allinone-package里面执行install.sh文件，产生报错，请问是什么原因

**Comment by zimu-yuxi** [comment]
root权限试一下

**Comment by wangzeyu135798** [comment]
![image](https://github.com/secretflow/secretpad/assets/39690172/1c88212b-9b9f-4bee-9dba-1243b42c4cab)
请问红框里面 的文件是在哪里？在secretpad容器和解压后的压缩包中都未找到。

**Comment by zimu-yuxi** [comment]
这是我们的示例路径，仅供参考，/users/lucky/换成自己的机器路径。

**Comment by wangzeyu135798** [comment]
![image](https://github.com/secretflow/secretpad/assets/39690172/9b6a08ae-e549-4afe-91ca-ef9900dcf860)
想问一下，db文件夹是config文件夹同目录新建的，./update-sql.sh 这个文件是在哪里？

**Comment by wangzeyu135798** [comment]
Logging system failed to initialize using configuration from 'null'
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[rootFile] - Failed to create parent directories for [/app/log/secretpad.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[rootFile] - openFile(/app/log/secretpad.log,true) call failed. java.io.FileNotFoundException: /app/log/secretpad.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[dataSync] - Failed to create parent directories for [/app/log/data-sync.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[dataSync] - openFile(/app/log/data-sync.log,true) call failed. java.io.FileNotFoundException: /app/log/data-sync.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorFile] - Failed to create parent directories for [/app/log/error.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorFile] - openFile(/app/log/error.log,true) call failed. java.io.FileNotFoundException: /app/log/error.log (No such file or directory)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.reportConfigurationErrorsIfNecessary(LogbackLoggingSystem.java:275)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:253)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:189)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:332)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:298)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:174)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:133)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:319)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.secretflow.secretpad.web.SecretPadApplication.main(SecretPadApplication.java:59)
	Suppressed: java.io.FileNotFoundException: /app/log/secretpad.log (No such file or directory)
		at java.base/java.io.FileOutputStream.open0(Native Method)
		at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
		at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
		at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
		at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:206)
		at ch.qos.logback.core.FileAppender.start(FileAppender.java:126)
		at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:104)
		at ch.qos.logback.core.model.processor.AppenderModelHandler.postHandle(AppenderModelHandler.java:84)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:257)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
		at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
		at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:208)
		at org.springframework.boot.logging.logback.SpringBootJoranConfigurator.processModel(SpringBootJoranConfigurator.java:122)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:170)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:122)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:65)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:285)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.lambda$loadConfiguration$1(LogbackLoggingSystem.java:247)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.withLoggingSuppressed(LogbackLoggingSystem.java:460)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:242)
		... 23 more
	Suppressed: java.io.FileNotFoundException: /app/log/data-sync.log (No such file or directory)
		at java.base/java.io.FileOutputStream.open0(Native Method)
		at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
		at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
		at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
		at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:206)
		at ch.qos.logback.core.FileAppender.start(FileAppender.java:126)
		at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:104)
		at ch.qos.logback.core.model.processor.AppenderModelHandler.postHandle(AppenderModelHandler.java:84)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:257)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
		at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
		at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:208)
		at org.springframework.boot.logging.logback.SpringBootJoranConfigurator.processModel(SpringBootJoranConfigurator.java:122)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:170)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:122)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:65)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:285)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.lambda$loadConfiguration$1(LogbackLoggingSystem.java:247)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.withLoggingSuppressed(LogbackLoggingSystem.java:460)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:242)
		... 23 more
	Suppressed: java.io.FileNotFoundException: /app/log/error.log (No such file or directory)
		at java.base/java.io.FileOutputStream.open0(Native Method)
		at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
		at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
		at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
		at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:206)
		at ch.qos.logback.core.FileAppender.start(FileAppender.java:126)
		at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:104)
		at ch.qos.logback.core.model.processor.AppenderModelHandler.postHandle(AppenderModelHandler.java:84)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:257)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
		at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
		at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:208)
		at org.springframework.boot.logging.logback.SpringBootJoranConfigurator.processModel(SpringBootJoranConfigurator.java:122)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:170)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:122)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:65)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:285)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.lambda$loadConfiguration$1(LogbackLoggingSystem.java:247)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.withLoggingSuppressed(LogbackLoggingSystem.java:460)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:242)
		... 23 more
Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[rootFile] - Failed to create parent directories for [/app/log/secretpad.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[rootFile] - openFile(/app/log/secretpad.log,true) call failed. java.io.FileNotFoundException: /app/log/secretpad.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[dataSync] - Failed to create parent directories for [/app/log/data-sync.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[dataSync] - openFile(/app/log/data-sync.log,true) call failed. java.io.FileNotFoundException: /app/log/data-sync.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorFile] - Failed to create parent directories for [/app/log/error.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorFile] - openFile(/app/log/error.log,true) call failed. java.io.FileNotFoundException: /app/log/error.log (No such file or directory)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:347)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:298)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:174)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:133)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:319)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.secretflow.secretpad.web.SecretPadApplication.main(SecretPadApplication.java:59)
Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[rootFile] - Failed to create parent directories for [/app/log/secretpad.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[rootFile] - openFile(/app/log/secretpad.log,true) call failed. java.io.FileNotFoundException: /app/log/secretpad.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[dataSync] - Failed to create parent directories for [/app/log/data-sync.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[dataSync] - openFile(/app/log/data-sync.log,true) call failed. java.io.FileNotFoundException: /app/log/data-sync.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorFile] - Failed to create parent directories for [/app/log/error.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorFile] - openFile(/app/log/error.log,true) call failed. java.io.FileNotFoundException: /app/log/error.log (No such file or directory)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.reportConfigurationErrorsIfNecessary(LogbackLoggingSystem.java:275)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:253)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:189)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:332)
	... 19 more
	Suppressed: java.io.FileNotFoundException: /app/log/secretpad.log (No such file or directory)
		at java.base/java.io.FileOutputStream.open0(Native Method)
		at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
		at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
		at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
		at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:206)
		at ch.qos.logback.core.FileAppender.start(FileAppender.java:126)
		at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:104)
		at ch.qos.logback.core.model.processor.AppenderModelHandler.postHandle(AppenderModelHandler.java:84)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:257)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
		at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
		at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:208)
		at org.springframework.boot.logging.logback.SpringBootJoranConfigurator.processModel(SpringBootJoranConfigurator.java:122)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:170)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:122)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:65)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:285)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.lambda$loadConfiguration$1(LogbackLoggingSystem.java:247)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.withLoggingSuppressed(LogbackLoggingSystem.java:460)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:242)
		... 23 more
	Suppressed: java.io.FileNotFoundException: /app/log/data-sync.log (No such file or directory)
		at java.base/java.io.FileOutputStream.open0(Native Method)
		at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
		at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
		at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
		at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:206)
		at ch.qos.logback.core.FileAppender.start(FileAppender.java:126)
		at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:104)
		at ch.qos.logback.core.model.processor.AppenderModelHandler.postHandle(AppenderModelHandler.java:84)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:257)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
		at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
		at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:208)
		at org.springframework.boot.logging.logback.SpringBootJoranConfigurator.processModel(SpringBootJoranConfigurator.java:122)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:170)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:122)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:65)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:285)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.lambda$loadConfiguration$1(LogbackLoggingSystem.java:247)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.withLoggingSuppressed(LogbackLoggingSystem.java:460)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:242)
		... 23 more
	Suppressed: java.io.FileNotFoundException: /app/log/error.log (No such file or directory)
		at java.base/java.io.FileOutputStream.open0(Native Method)
		at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
		at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
		at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
		at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:206)
		at ch.qos.logback.core.FileAppender.start(FileAppender.java:126)
		at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:104)
		at ch.qos.logback.core.model.processor.AppenderModelHandler.postHandle(AppenderModelHandler.java:84)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:257)
		at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
		at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
		at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:208)
		at org.springframework.boot.logging.logback.SpringBootJoranConfigurator.processModel(SpringBootJoranConfigurator.java:122)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:170)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:122)
		at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:65)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:285)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.lambda$loadConfiguration$1(LogbackLoggingSystem.java:247)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.withLoggingSuppressed(LogbackLoggingSystem.java:460)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:242)
		... 23 more

Process finished with exit code 1
本地启动的时候报了这个错，请问是为什么？

**Comment by wangzeyu135798** [comment]
![0e44d63996e46610b88f178bfc9bf05](https://github.com/secretflow/secretpad/assets/39690172/770986bc-1d45-4048-8425-1d658336e665)
请问这里是什么问题？

**Comment by wangzeyu135798** [comment]
![image](https://github.com/secretflow/secretpad/assets/39690172/c77ec579-f75a-42bc-b89e-a4850758e79a)
![image](https://github.com/secretflow/secretpad/assets/39690172/7f3fda0d-9f62-4731-92b7-4659cac70601)
![image](https://github.com/secretflow/secretpad/assets/39690172/8fc09e2a-024d-433a-a921-d9178dc863f6)
你好，我这边启动不起来，是有什么内容配置错误了吗？

**Comment by byeyang** [comment]
运行java -jar -Dspring.profiles.active=dev /home/secretpad/target/secretpad.jar的时候报错了：

2024-05-09T01:19:52.504+08:00 ERROR 142559 --- [ault-executor-0] o.s.s.m.integration.job.JobManager       : watchJob onError: UNAVAILABLE: Network closed for unknown reason

io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.Status.asRuntimeException(Status.java:539)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:576)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:757)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:736)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
排除了很久都不行，呜呜呜..............

**Comment by wenkesong-li** [comment]
你好，原因应该是连不上kuscia，请确定一下部署方式。 可以查看文档重新操作一下

https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/latest/dbd670doqfio1puq#hfHFD

**Comment by wangzeyu135798** [comment]
> 你好，原因应该是连不上kuscia，请确定一下部署方式。 可以查看文档重新操作一下
> 
> https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/latest/dbd670doqfio1puq#hfHFD
按照你说的这种方式部署的MVP，没有加-P参数，默认的protocol是tls，启动的时候也是报关于tls的错误。
![image](https://github.com/secretflow/secretpad/assets/39690172/80bd22cd-9d22-4547-a735-41654361e2e5)
![image](https://github.com/secretflow/secretpad/assets/39690172/1883ade2-e105-41bd-bd92-46c08432ea41)
请问该如何修改。

**Comment by zimu-yuxi** [comment]
1.确认pad和kuscia是在同一机器下
2.确认下项目启动时是否加了jvm参数：-Dspring.profiles.active=dev
3.修改application-dev.yaml的配置，ip为宿主机的出口IP，gateway端口为容器1080映射的宿主机端口，grpc api的端口为容器1083映射的宿主机端口

**Comment by wangzeyu135798** [comment]
> 1.确认pad和kuscia是在同一机器下 2.确认下项目启动时是否加了jvm参数：-Dspring.profiles.active=dev 3.修改application-dev.yaml的配置，ip为宿主机的出口IP，gateway端口为容器1080映射的宿主机端口，grpc api的端口为容器1083映射的宿主机端口

关于第三点有个问题，ip是在application-dev.yaml的什么地方？
下图所示的node-id中NODE_ID后面就是直接写-n的参数吗，替换掉kuscia-system？

**Comment by wangzeyu135798** [comment]
> 1.确认pad和kuscia是在同一机器下 2.确认下项目启动时是否加了jvm参数：-Dspring.profiles.active=dev 3.修改application-dev.yaml的配置，ip为宿主机的出口IP，gateway端口为容器1080映射的宿主机端口，grpc api的端口为容器1083映射的宿主机端口

关于第三点有个问题，ip是在application-dev.yaml的什么地方？
下图所示的node-id中NODE_ID后面就是直接写-n的参数吗，替换掉kuscia-system？
![image](https://github.com/secretflow/secretpad/assets/39690172/83544f44-4c7d-4e1b-8d3f-de34c24a9aab)

**Comment by zimu-yuxi** [comment]
> > 1.确认pad和kuscia是在同一机器下 2.确认下项目启动时是否加了jvm参数：-Dspring.profiles.active=dev 3.修改application-dev.yaml的配置，ip为宿主机的出口IP，gateway端口为容器1080映射的宿主机端口，grpc api的端口为容器1083映射的宿主机端口
> 
> 关于第三点有个问题，ip是在application-dev.yaml的什么地方？ 下图所示的node-id中NODE_ID后面就是直接写-n的参数吗，替换掉kuscia-system？ ![image](https://private-user-images.githubusercontent.com/39690172/329479700-83544f44-4c7d-4e1b-8d3f-de34c24a9aab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjI2ODQsIm5iZiI6MTcxNTMyMjM4NCwicGF0aCI6Ii8zOTY5MDE3Mi8zMjk0Nzk3MDAtODM1NDRmNDQtNGM3ZC00ZTFiLThkM2YtZGUzNGMyNGE5YWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA2MjYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YzNmMzI2ZmY4NDNhMTc4Yjc2ZTVjNGM4ZmMzMTU4ZmE3ZWJlYzc0NmUxNDVhMWI4MjJhNGRkZWQwYzY3NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.brgjVieNiUX7GBGNzh0dT1UDap4XF31olJyi8FmtrQw)

gateway的那个address

**Comment by wangzeyu135798** [comment]
![image](https://github.com/secretflow/secretpad/assets/39690172/2fa053fe-5819-4a01-bf5c-6f192d91d067)
![image](https://github.com/secretflow/secretpad/assets/39690172/9b972d64-cddb-4f92-a850-089f0bac744c)
启动好像不报错，但是login页面显示不出来，这是为什么？

**Comment by zimu-yuxi** [comment]
前端代码启动了吗。确认下前端代码的代理地址哈

**Comment by wangzeyu135798** [comment]
可以了，谢谢

**Comment by LookingName** [comment]
您好  pad和kuscia不在同一机器下可以么

**Comment by wangzeyu135798** [comment]
没试过 我的是在一台机器上启动的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月28日(周二) 下午2:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [secretflow/secretpad] secetpad本地启动报错 (Issue #64)




 
您好  pad和kuscia不在同一机器下可以么

**Comment by wenkesong-li** [comment]
> 您好 pad和kuscia不在同一机器下可以么

支持的，kuscia安装时使用notls
