### ISSUE TITLE
secretpad本地启动 报错

### ISSUE THREAD

**Issue by byeyang** [secretflow/secretpad#65]
运行java -jar -Dspring.profiles.active=dev /home/secretpad/target/secretpad.jar的时候报错了：

2024-05-09T01:19:52.504+08:00 ERROR 142559 --- [ault-executor-0] o.s.s.m.integration.job.JobManager : watchJob onError: UNAVAILABLE: Network closed for unknown reason

io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
at io.grpc.Status.asRuntimeException(Status.java:539)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:576)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:757)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:736)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
排除了很久都不行，呜呜呜..............

我的环境：
<img width="851" alt="微信图片_20240509160104" src="https://github.com/secretflow/secretpad/assets/67679201/f71d7b0b-925d-446d-adfb-6d3760b4f9f9">

<img width="1169" alt="微信图片_20240509160320" src="https://github.com/secretflow/secretpad/assets/67679201/2ae6ccc7-1038-4651-9dbf-18380ed24490">

<img width="586" alt="微信图片_20240509160527" src="https://github.com/secretflow/secretpad/assets/67679201/4615c004-f87b-4019-8749-95f42c97f394">

<img width="689" alt="微信图片_20240509160613" src="https://github.com/secretflow/secretpad/assets/67679201/97034ead-852c-4ffa-b058-87e88221efca">

拜托了 大佬们！

**Comment by wenkesong-li** [comment]
你好，原因应该是连不上kuscia，请确定一下部署方式。 可以查看文档重新操作一下

https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/latest/dbd670doqfio1puq#hfHFD

**Comment by byeyang** [comment]
你好，我重新尝试了，请问这样的配置正确吗
![image](https://github.com/secretflow/secretpad/assets/67679201/3dbfa7fa-e83a-46d8-b708-0e0e6f6f2cc8)
![image](https://github.com/secretflow/secretpad/assets/67679201/3faeb51c-9311-4270-943e-af66d8d5ff0c)

我前面的配置是p2p的，这样的：（容器已经启动）
sh install.sh autonomy -n bot -s 8080 -g 40803 -k 40802 -p 10080 -q 13081 -P mtls
sh install.sh autonomy -n bot -s 8082 -g 50803 -k 50802 -p 20080 -q 23081 -P mtls

**Comment by wenkesong-li** [comment]
你好 关于你的问题我看你在https://github.com/secretflow/secretpad/issues/64中也有询问
应该和你的问题一样，可以参考一下

**Comment by byeyang** [comment]
好的，感谢我已经能启动了，请问启动后访问http://192.168.xxxx:8080  页面空白正常吗，是什么问题，需要怎么配置

> 你好 关于你的问题我看你在[https://github.com/secretflow/secretpad/issues/64中也有询问](https://github.com/secretflow/secretpad/issues/64%E4%B8%AD%E4%B9%9F%E6%9C%89%E8%AF%A2%E9%97%AE) 应该和你的问题一样，可以参考一下

**Comment by byeyang** [comment]
已经成功启动，谢谢，有帮助。

**Comment by byeyang** [comment]
2024-05-13T21:01:47.224+08:00  INFO 36249 --- [           main] o.s.secretpad.web.init.P2pDataInit       : P2pDataInit start
2024-05-13T21:01:48.131+08:00  INFO 36249 --- [           main] .s.a.AnnotationAsyncExecutionInterceptor : More than one TaskExecutor bean found within the context, and none is named 'taskExecutor'. Mark one of them as primary or name it 'taskExecutor' (possibly as an alias) in order to use it for async processing: [dataSyncThreadPool, taskScheduler]
2024-05-13T21:01:48.178+08:00  INFO 36249 --- [           main] o.s.secretpad.web.init.P2pDataInit       : ownerId_cache init {}
2024-05-13T21:01:48.208+08:00  WARN 36249 --- [           main] o.s.secretpad.web.init.MasterRouteInit   : node router list is empty
2024-05-13T21:01:48.240+08:00  INFO 36249 --- [           main] o.s.s.service.listener.JobSyncListener   : jobManager startSync....
2024-05-13T21:01:48.253+08:00  INFO 36249 --- [           main] o.s.secretpad.web.SecretPadApplication   : SecretPad start success, http://127.0.0.1:2443 innerHttpPort:9001 Profile:[dev]
可以帮我看看P2P模式下的启动问题吗，这个是启动了 但是网页无法访问，访问超时。

**Comment by wenkesong-li** [comment]
你好，麻烦贴一下完成的启动日志，和你浏览器打开网页的截图~

**Comment by byeyang** [comment]
> 你好，麻烦贴一下完成的启动日志，和你浏览器打开网页的截图~

麻烦您了，感谢感谢~~~

**Comment by wenkesong-li** [comment]
你好，查看到你应该在服务器上进行的，可以看下服务器防火墙是否放行了端口


可以加一下技术支持微信号 方便更快的push问题~

https://github.com/secretflow/secretpad/blob/main/README.zh-CN.md
