### ISSUE TITLE
PSI：KKRT 和RR22 协议OOM

### ISSUE THREAD

**Issue by gxcuit** [secretflow/secretpad#84]
Hi， 我使用secretpad， docker 进行p2p 进行部署，版本信息如下

```
secretpadImage版本：0.7.1b0
secretflowServingImage版本：0.3.1b0
kusciaImage版本：0.8.0b0
secretflowImage版本：1.6.1b0
```

我发现，psi 只有ecdh协议正常，kkrt和rr22 报OOM的错误. 数据规模不大，1000左右。 docker 的内存提高到了8g

![image](https://github.com/secretflow/secretpad/assets/18736196/99da3c0c-eeb2-46be-8c24-24e20887b1ee)

日志如下

<details> 
```
2024-06-11 18:29:59 INFO the jobId=mgey, taskId=mgey-jjhodnxr-node-35 start ...
2024-06-11 18:30:25 INFO the jobId=mgey, taskId=mgey-jjhodnxr-node-35 failed: party alice failed msg: container[secretflow] terminated state reason "Error", message: "r this task could not be computed:
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
\tclass_name: SPURuntime
\tactor_id: 6b8ff9d344e3fb1584fa53a701000000
\tpid: 728
\tnamespace: 2d854d99-9d0a-4226-8f15-0b81472f9b80
\tip: mgey-jjhodnxr-node-35-0-global.alice.svc
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"/usr/local/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner
    self.run()
  File \"/usr/local/lib/python3.10/threading.py\", line 953, in run
    self._target(*self._args, **self._kwargs)
  File \"/usr/local/lib/python3.10/site-packages/fed/_private/message_queue.py\", line 51, in _loop
    res = self._msg_handler(message)
  File \"/usr/local/lib/python3.10/site-packages/fed/cleanup.py\", line 47, in <lambda>
    lambda msg: self._process_data_sending_task_return(msg),
  File \"/usr/local/lib/python3.10/site-packages/fed/cleanup.py\", line 166, in _process_data_sending_task_return
    send(
  File \"/usr/local/lib/python3.10/site-packages/fed/proxy/barriers.py\", line 502, in send
    get_global_context().get_cleanup_manager().push_to_sending(
AttributeError: 'NoneType' object has no attribute 'get_cleanup_manager'
Traceback (most recent call last):
  File \"/usr/local/lib/python3.10/runpy.py\", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File \"/usr/local/lib/python3.10/runpy.py\", line 86, in _run_code
    exec(code, run_globals)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py\", line 547, in <module>
    main()
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1157, in __call__
    return self.main(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1078, in main
    rv = self.invoke(ctx)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 783, in invoke
    return __callback(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py\", line 527, in main
    res = comp_eval(sf_node_eval_param, storage_config, sf_cluster_config)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/entry.py\", line 166, in comp_eval
    res = comp.eval(
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/component.py\", line 1131, in eval
    raise e from None
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/component.py\", line 1126, in eval
    ret = self.__eval_callback(ctx=ctx, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/preprocessing/data_prep/psi.py\", line 371, in two_party_balanced_psi_eval_fn
    report = spu.psi(
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/spu.py\", line 2097, in psi
    return dispatch(
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/register.py\", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/device/register.py\", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/kernels/spu.py\", line 615, in psi
    return sfd.get(res)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/primitive.py\", line 156, in get
    return fed.get(object_refs)
  File \"/usr/local/lib/python3.10/site-packages/fed/api.py\", line 621, in get
    values = ray.get(ray_refs)
  File \"/usr/local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py\", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper
    return func(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/ray/_private/worker.py\", line 2626, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
\tclass_name: SPURuntime
\tactor_id: 6b8ff9d344e3fb1584fa53a701000000
\tpid: 728
\tnamespace: 2d854d99-9d0a-4226-8f15-0b81472f9b80
\tip: mgey-jjhodnxr-node-35-0-global.alice.svc
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=728)\x1b[0m [2024-06-11 10:30:21.391] [info] [launch.cc:119] PSI config: {\"protocol_config\":{\"protocol\":\"PROTOCOL_KKRT\",\"role\":\"ROLE_RECEIVER\",\"broadcast_result\":true},\"input_config\":{\"type\":\"IO_TYPE_FILE_CSV\",\"path\":\"/home/kuscia/var/storage/data/breast_new2_590923962.csv\"},\"output_config\":{\"type\":\"IO_TYPE_FILE_CSV\",\"path\":\"/home/kuscia/var/storage/data/mgey-jjhodnxr-node-35-output-0\"},\"keys\":[\"id\"],\"skip_duplicates_check\":true,\"left_side\":\"ROLE_RECEIVER\"}
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=728)\x1b[0m [2024-06-11 10:30:21.391] [info] [receiver.cc:37] [KkrtPsiReceiver::Init] start
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=728)\x1b[0m [2024-06-11 10:30:21.391] [info] [interface.cc:78] [AbstractPsiParty::Init] start
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=728)\x1b[0m [2024-06-11 10:30:21.397] [info] [interface.cc:136] [AbstractPsiParty::Init][Check csv pre-process] start
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=728)\x1b[0m [2024-06-11 10:30:21.401] [info] [interface.cc:145] [AbstractPsiParty::Init][Check csv pre-process] end
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=728)\x1b[0m [2024-06-11 10:30:21.407] [info] [interface.cc:183] [AbstractPsiParty::Init] end
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=728)\x1b[0m [2024-06-11 10:30:21.407] [info] [receiver.cc:42] [KkrtPsiReceiver::Init] end
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=728)\x1b[0m [2024-06-11 10:30:21.407] [info] [receiver.cc:47] [KkrtPsiReceiver::PreProcess] start
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=728)\x1b[0m [2024-06-11 10:30:21.408] [info] [bucket_psi.cc:514] psi protocol=2, rank=0 item_size=569
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=728)\x1b[0m [2024-06-11 10:30:21.408] [info] [bucket_psi.cc:514] psi protocol=2, rank=1 item_size=569
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=728)\x1b[0m [2024-06-11 10:30:21.412] [info] [arrow_csv_batch_provider.cc:75] Reach the end of csv file /home/kuscia/var/storage/data/breast_new2_590923962.csv.
\x1b[36m(SPURuntime(device_id=None, party=alice) pid=728)\x1b[0m [2024-06-11 10:30:21.412] [info] [arrow_csv_batch_provider.cc:75] Reach the end of csv file /home/kuscia/var/storage/data/breast_new2_590923962.csv.
\x1b[33m(raylet)\x1b[0m A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff6b8ff9d344e3fb1584fa53a701000000 Worker ID: b81e69dc5c23a765d1f5cc5d06e2c59a9cedc33be29ebb1466e66f27 Node ID: c62d983dc71ae67ccb66a649c2e65e1f30b1c3196521987b6ce325b6 Worker IP address: mgey-jjhodnxr-node-35-0-global.alice.svc Worker port: 10014 Worker PID: 728 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
"
```

</detalis>

**Comment by gxcuit** [comment]
> hi @gxcuit 您可以将数据文件脱敏后发出来吗？

Hi, @lq0404510 Thanks for your reply
----

[breast_new1.csv](https://github.com/user-attachments/files/15812657/breast_new1.csv)
[breast_new2.csv](https://github.com/user-attachments/files/15812658/breast_new2.csv)

不知道是不是我机器太老的原因？

宿主机 Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz hyporvisor VMware ESXi, 6.7.0, 8169922

```
2024-06-11T18:30:21.439034746+08:00 stderr F �[33m(raylet)�[0m [2024-06-11 10:30:17,901 I 728 728] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
2024-06-11T18:30:21.553161584+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m *** SIGILL received at time=1718101821 on cpu 3 ***
2024-06-11T18:30:21.553204936+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m PC: @     0x7f2373fdfa32  (unknown)  yacl::AvxTranspose128()
2024-06-11T18:30:21.553220273+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m     @     0x7f25dc012ce0  (unknown)  (unknown)
2024-06-11T18:30:21.553266017+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m     @     0x7f2373f399ad       9536  yacl::crypto::IknpOtExtSend()
2024-06-11T18:30:21.666765888+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m     @     0x7f2373f34029        464  psi::kkrt::GetKkrtOtReceiverOptions()
2024-06-11T18:30:21.666827943+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m     @     0x7f2373d60ab0       1536  psi::RunPsi()
2024-06-11T18:30:21.666851651+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m     @     0x7f2373d56205        384  psi::BindLibs()::{lambda()#3}::operator()()
2024-06-11T18:30:21.666873831+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m     @     0x7f2373d56483        176  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
2024-06-11T18:30:21.666925956+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m     @     0x7f2373d3843d        736  pybind11::cpp_function::dispatcher()
2024-06-11T18:30:21.66694947+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m     @           0x4fc697  (unknown)  cfunction_call
2024-06-11T18:30:21.666971214+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m     @ ... and at least 1 more frames
2024-06-11T18:30:21.666991882+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m [2024-06-11 10:30:21,644 E 728 728] logging.cc:361: *** SIGILL received at time=1718101821 on cpu 3 ***
2024-06-11T18:30:21.667012095+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m [2024-06-11 10:30:21,644 E 728 728] logging.cc:361: PC: @     0x7f2373fdfa32  (unknown)  yacl::AvxTranspose128()
2024-06-11T18:30:21.667052926+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m [2024-06-11 10:30:21,644 E 728 728] logging.cc:361:     @     0x7f25dc012ce0  (unknown)  (unknown)
2024-06-11T18:30:21.667076384+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m [2024-06-11 10:30:21,645 E 728 728] logging.cc:361:     @     0x7f2373f399ad       9536  yacl::crypto::IknpOtExtSend()
2024-06-11T18:30:21.66709696+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m [2024-06-11 10:30:21,645 E 728 728] logging.cc:361:     @     0x7f2373f34029        464  psi::kkrt::GetKkrtOtReceiverOptions()
2024-06-11T18:30:21.667151046+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m [2024-06-11 10:30:21,645 E 728 728] logging.cc:361:     @     0x7f2373d60ab0       1536  psi::RunPsi()
2024-06-11T18:30:21.667214121+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m [2024-06-11 10:30:21,645 E 728 728] logging.cc:361:     @     0x7f2373d56205        384  psi::BindLibs()::{lambda()#3}::operator()()
2024-06-11T18:30:21.667341457+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m [2024-06-11 10:30:21,645 E 728 728] logging.cc:361:     @     0x7f2373d56483        176  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
2024-06-11T18:30:21.667410986+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m [2024-06-11 10:30:21,645 E 728 728] logging.cc:361:     @     0x7f2373d3843d        736  pybind11::cpp_function::dispatcher()
2024-06-11T18:30:21.66743628+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m [2024-06-11 10:30:21,645 E 728 728] logging.cc:361:     @           0x4fc697  (unknown)  cfunction_call
2024-06-11T18:30:21.667457034+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m [2024-06-11 10:30:21,645 E 728 728] logging.cc:361:     @ ... and at least 1 more frames
2024-06-11T18:30:21.667478061+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m Fatal Python error: Illegal instruction
2024-06-11T18:30:21.667499926+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m 
2024-06-11T18:30:21.667520369+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m Stack (most recent call first):
2024-06-11T18:30:21.667573281+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m   File "/usr/local/lib/python3.10/site-packages/spu/psi.py", line 118 in psi
2024-06-11T18:30:21.667596458+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m   File "/usr/local/lib/python3.10/site-packages/secretflow/device/device/spu.py", line 1379 in psi
2024-06-11T18:30:21.667616909+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m   File "/usr/local/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 467 in _resume_span
2024-06-11T18:30:21.667636415+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m   File "/usr/local/lib/python3.10/site-packages/ray/_private/function_manager.py", line 726 in actor_method_executor
2024-06-11T18:30:21.667676736+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m   File "/usr/local/lib/python3.10/site-packages/ray/_private/worker.py", line 847 in main_loop
2024-06-11T18:30:21.667698507+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m   File "/usr/local/lib/python3.10/site-packages/ray/_private/workers/default_worker.py", line 282 in <module>
2024-06-11T18:30:21.667746345+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m 
2024-06-11T18:30:21.668545347+08:00 stderr F �[36m(SPURuntime(device_id=None, party=alice) pid=728)�[0m Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, ray._raylet, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, jaxlib.cpu_feature_guard, grpc._cython.cygrpc, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.tslib, pandas._libs.lib, pandas._libs.hashing, pyarrow.lib, pyarrow._hdfsio, pandas._libs.ops, pyarrow._compute, pandas._libs.arrays, pandas._libs.index, pandas._libs.join, pandas._libs.sparse, pandas._libs.reduction, pandas._libs.indexing, pandas._libs.internals, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.tslibs.strptime, pandas._libs.groupby, pandas._libs.testing, pandas._libs.parsers, pandas._libs.json, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, sklearn.__check_build._check_build, scipy.special._ufuncs_cxx, scipy.special._cdflib, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, scipy.ndimage._nd_image, _ni_label, scipy.ndimage._ni_label, scipy.optimize._minpack2, scipy.optimize._group_columns, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.optimize._direct, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.special.cython_special, scipy.stats._stats, scipy.stats.beta_ufunc, scipy.stats._boost.beta_ufunc, scipy.stats.binom_ufunc, scipy.stats._boost.binom_ufunc, scipy.stats.nbinom_ufunc, scipy.stats._boost.nbinom_ufunc, scipy.stats.hypergeom_ufunc, scipy.stats._boost.hypergeom_ufunc, scipy.stats.ncf_ufunc, scipy.stats._boost.ncf_ufunc, scipy.stats.ncx2_ufunc, scipy.stats._boost.ncx2_ufunc, scipy.stats.nct_ufunc, scipy.stats._boost.nct_ufunc, scipy.stats.skewnorm_ufunc, scipy.stats._boost.skewnorm_ufunc, scipy.stats.invgauss_ufunc, scipy.stats._boost.invgauss_ufunc, scipy.interpolate._fitpack, scipy.interpolate.dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.stats._biasedurn, scipy.stats._levy_stable.levyst, scipy.stats._stats_pythran, scipy._lib._uarray._uarray, scipy.stats._ansari_swilk_statistics, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._mvn, scipy.stats._rcont.rcont, scipy.stats._unuran.unuran_wrapper, sklearn.utils._isfinite, sklearn.utils.murmurhash, sklearn.utils._openmp_helpers, sklearn.utils._logistic_sigmoid, sklearn.utils.sparsefuncs_fast, sklearn.preprocessing._csr_polynomial_expansion, sklearn.preprocessing._target_encoder_fast, pyarrow._json (total: 182)
2024-06-11T18:30:22.373640364+08:00 stderr F 2024-06-11 10:30:22.373 ERROR component.py:1129 [alice] -- [Anonymous_job] eval on domain: "data_prep"
```

**Comment by lq0404510** [comment]
@gxcuit 可以执行下这个命令：cat /proc/cpuinfo | grep avx，看下cpu的信息

**Comment by gxcuit** [comment]
> @gxcuit 可以执行下这个命令：cat /proc/cpuinfo | grep avx，看下cpu的信息

Hi, @lq0404510  Thanks for your reply.

我试过了，有avx，不过之前用FourQ，曾经报过 `FourQ requires AVX2 instruction`， 换别的曲线就可以了

cat /proc/cpuinfo | grep avx
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ibrs ibpb stibp tsc_adjust arat arch_capabilities
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ibrs ibpb stibp tsc_adjust arat arch_capabilities
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ibrs ibpb stibp tsc_adjust arat arch_capabilities
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ibrs ibpb stibp tsc_adjust arat arch_capabilities
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ibrs ibpb stibp tsc_adjust arat arch_capabilities
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ibrs ibpb stibp tsc_adjust arat arch_capabilities
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ibrs ibpb stibp tsc_adjust arat arch_capabilities
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ibrs ibpb stibp tsc_adjust arat arch_capabilities
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ibrs ibpb stibp tsc_adjust arat arch_capabilities
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ibrs ibpb stibp tsc_adjust arat arch_capabilities

**Comment by lq0404510** [comment]
您运行docker的服务器是通过windows创建的虚拟机进行的吗？如果是虚拟机进行运行的，先查看下物理机中是否存在avx avx2，如果有的话，将虚拟机配置中的cpu虚拟化打开，然后重启虚拟机。

**Comment by gxcuit** [comment]
> 您运行docker的服务器是通过windows创建的虚拟机进行的吗？如果是虚拟机进行运行的，先查看下物理机中是否存在avx avx2，如果有的话，将虚拟机配置中的cpu虚拟化打开，然后重启虚拟机。

Hi， docker 服务器是Linux 虚拟机， 跑在esxi上，Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz hyporvisor VMware ESXi, 6.7.0, 8169922 。

虚拟机中有avx，无avx2 。   

我换一个物理机试一试

**Comment by lq0404510** [comment]
您这边换过物理机以后，可以正常运行了吗？

**Comment by gxcuit** [comment]
> 您这边换过物理机以后，可以正常运行了吗？

抱歉还没来得及试，试过后在这反馈。Thanks

**Comment by gxcuit** [comment]
> 您这边换过物理机以后，可以正常运行了吗？

Hi, @lq0404510 

换过物理机后没问题了。但仍然比较奇怪，之前的机器是支持avx的

**Comment by lq0404510** [comment]
感谢您的回复，您目前换的物理机的cpu信息可以发下吗？cat /proc/cpuinfo | grep avx，关于您的疑问，我们目前也在分析，如果后续有相关信息，会与您同步
